################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
LD_SRCS := 
TODISASSEMBLE_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_UPPER_SRCS := 
TOPREPROCESS_SRCS := 
ASM_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Generated_Code \
Project_Settings/Startup_Code \
SDK/platform/devices/S32K144/startup \
SDK/platform/devices \
SDK/platform/drivers/src/adc \
SDK/platform/drivers/src/clock/S32K1xx \
SDK/platform/drivers/src/edma \
SDK/platform/drivers/src/ftm \
SDK/platform/drivers/src/interrupt \
SDK/platform/drivers/src/lin \
SDK/platform/drivers/src/lpuart \
SDK/platform/drivers/src/pins \
SDK/rtos/osif \
Sources/PLF/source/APPBT \
Sources/PLF/source/BSP/BSP_AD \
Sources/PLF/source/BSP/BSP_CAN \
Sources/PLF/source/BSP/BSP_DIO \
Sources/PLF/source/BSP/BSP_EEP \
Sources/PLF/source/BSP/BSP_I2C \
Sources/PLF/source/BSP/BSP_ICU \
Sources/PLF/source/BSP/BSP_MPU \
Sources/PLF/source/BSP/BSP_PDB \
Sources/PLF/source/BSP/BSP_PWM \
Sources/PLF/source/BSP/BSP_RST \
Sources/PLF/source/BSP/BSP_SUP \
Sources/PLF/source/BSP/BSP_TIM \
Sources/PLF/source/BSP/BSP_WDOG \
Sources/PLF/source/PLFICU/DAT/DAT_AD/DAT_ANA \
Sources/PLF/source/PLFICU/DAT/DAT_AD/DAT_PAN \
Sources/PLF/source/PLFICU/DAT/DAT_BAT \
Sources/PLF/source/PLFICU/DAT/DAT_BLDC \
Sources/PLF/source/PLFICU/DAT/DAT_BSDC \
Sources/PLF/source/PLFICU/DAT/DAT_CAN/DAT_CDL \
Sources/PLF/source/PLFICU/DAT/DAT_CAN/DAT_CIL \
Sources/PLF/source/PLFICU/DAT/DAT_CAN/DAT_CNL \
Sources/PLF/source/PLFICU/DAT/DAT_CAN/DAT_CNM \
Sources/PLF/source/PLFICU/DAT/DAT_CAN/DAT_CPL \
Sources/PLF/source/PLFICU/DAT/DAT_CAN/DAT_CTL \
Sources/PLF/source/PLFICU/DAT/DAT_COM \
Sources/PLF/source/PLFICU/DAT/DAT_COM/DAT_J1939 \
Sources/PLF/source/PLFICU/DAT/DAT_CPU \
Sources/PLF/source/PLFICU/DAT/DAT_DIO/DAT_DIN \
Sources/PLF/source/PLFICU/DAT/DAT_DIO/DAT_DOU \
Sources/PLF/source/PLFICU/DAT/DAT_DIO/DAT_PIN \
Sources/PLF/source/PLFICU/DAT/DAT_DIO/DAT_POU \
Sources/PLF/source/PLFICU/DAT/DAT_DTC/DAT_DDB \
Sources/PLF/source/PLFICU/DAT/DAT_DTC/DAT_DDI \
Sources/PLF/source/PLFICU/DAT/DAT_DTC/DAT_DII \
Sources/PLF/source/PLFICU/DAT/DAT_EEP/DAT_DBK \
Sources/PLF/source/PLFICU/DAT/DAT_EEP/DAT_DEA \
Sources/PLF/source/PLFICU/DAT/DAT_EEP/DAT_EEP \
Sources/PLF/source/PLFICU/DAT/DAT_EEP/DAT_OBK \
Sources/PLF/source/PLFICU/DAT/DAT_EEP/DAT_PEE \
Sources/PLF/source/PLFICU/DAT/DAT_EEP/DAT_SBK \
Sources/PLF/source/PLFICU/DAT/DAT_MOD \
Sources/PLF/source/PLFICU/HAL \
Sources/PLF/source/PLFICU/J1939ProtocolStack/CanDriver \
Sources/PLF/source/PLFICU/J1939ProtocolStack/CanIf \
Sources/PLF/source/PLFICU/J1939ProtocolStack/Dem \
Sources/PLF/source/PLFICU/J1939ProtocolStack/Demo \
Sources/PLF/source/PLFICU/J1939ProtocolStack/Det \
Sources/PLF/source/PLFICU/J1939ProtocolStack/J1939Dcm \
Sources/PLF/source/PLFICU/J1939ProtocolStack/J1939Tp \
Sources/PLF/source/PLFICU/J1939ProtocolStack/J1939_INCLUDE \
Sources/PLF/source/PLFICU/J1939ProtocolStack/OsekNm \
Sources/PLF/source/PLFICU/LAP/LAP_CAN \
Sources/PLF/source/PLFICU/LAP/LAP_CPULOAD/Include \
Sources/PLF/source/PLFICU/LAP/LAP_CPULOAD/Portable \
Sources/PLF/source/PLFICU/LAP/LAP_CPULOAD \
Sources/PLF/source/PLFICU/LAP/LAP_DIAG/LAP_DIA \
Sources/PLF/source/PLFICU/LAP/LAP_DIAG/LAP_DTC \
Sources/PLF/source/PLFICU/LAP/LAP_DIAG/LAP_IOC \
Sources/PLF/source/PLFICU/LAP/LAP_DIAG/LAP_RWA \
Sources/PLF/source/PLFICU/LAP/LAP_DIAG/LAP_RWI \
Sources/PLF/source/PLFICU/LAP/LAP_DIAG/LAP_SEA \
Sources/PLF/source/PLFICU/LAP/LAP_DIAG/LAP_SRI \
Sources/PLF/source/PLFICU/LAP/LAP_EEP \
Sources/PLF/source/PLFICU/LAP/LAP_RST \
Sources/PLF/source/PLFICU/LAP/LAP_RUNIN \
Sources/PLF/source/PLFICU/LAP/LAP_SUP \
Sources/PLF/source/PLFICU/LDB/LDB_AD \
Sources/PLF/source/PLFICU/LDB/LDB_CAN \
Sources/PLF/source/PLFICU/LDB/LDB_DIN \
Sources/PLF/source/PLFICU/LDB/LDB_DOU \
Sources/PLF/source/PLFICU/LDB/LDB_EEP \
Sources/PLF/source/PLFICU/LDB/LDB_ICU \
Sources/PLF/source/PLFICU/LDB/LDB_INT \
Sources/PLF/source/PLFICU/LDB/LDB_RST \
Sources/PLF/source/PLFICU/LDB/LDB_SUP \
Sources/PLF/source/PLFICU/LDB/LDB_TIM \
Sources/PLF/source/PLFICU/LIB/LIB_API \
Sources/PLF/source/PLFICU/LIB/LIB_CRC \
Sources/PLF/source/PLFICU/LIB/LIB_ITP \
Sources/PLF/source/PLFICU/LIB/LIB_QUEUE \
Sources/PLF/source/PLFICU/LIB/LIB_VER \
Sources/PLF/source/PLFICU/SER/SER_Control \
Sources/PLF/source/PLFICU/SER/SER_DAT \
Sources/PLF/source/PLFICU/TOS/TOS_ALA \
Sources/PLF/source/PLFICU/TOS/TOS_JIL \
Sources/PLF/source/PLFICU/TOS/TOS_ORD \
Sources/PLF/source/PLFICU/TOS/TOS_PERFCNT \
Sources/PLF/source/PLFICU/TOS/TOS_SEQ \
Sources/PLF/source/PLFICU/TOS/TOS_SIG \
Sources/PLF/source/PLFICU/TOS/TOS_TPO \
Sources \

