//This file was generated by DAT_DTC_CFG.xlsm
#ifndef _QAC_

#endif

#if !defined(DTC_DEFINE_DTC_ID_ENUM) && !defined(DTC_DEFINE_STRUCT)

#error >>>> this header is never included directly ! <<<<

#endif

//FunCom= functional component

#undef DTC_DEFINE

#if defined( DTC_DEFINE_DTC_ID_ENUM )
#define DTC_DEFINE( DTC_ID, DTCFunCom, DefectType, DefectCode, DTCTriggerValue, DTCConfirmedStep, DTCHealedStep)    DTC_ID,
#elif defined( DTC_DEFINE_STRUCT )
#define DTC_DEFINE( DTC_ID, DTCFunCom, DefectType, DefectCode, DTCTriggerValue, DTCConfirmedStep, DTCHealedStep)\
    { DTCFunCom, DefectType, DefectCode, DTCTriggerValue, DTCConfirmedStep, DTCHealedStep},
#endif

DTC_DEFINE(eDTCIDAngleSenPowOverVol,eDTCFunCom_AngleSenPowOverVol, 0xE3,0x5E0,1,1,1)

DTC_DEFINE(eDTCIDAngleSenPowUnderVol,eDTCFunCom_AngleSenPowUnderVol, 0xE4,0x5E0,1,1,1)

DTC_DEFINE(eDTCIDAngleSenOutFault,eDTCFunCom_AngleSenOutFault, 0xE2,0x6E0,1,1,1)

DTC_DEFINE(eDTCIDAngleSenOutOverVol,eDTCFunCom_AngleSenOutOverVol, 0xE3,0x6E0,1,1,1)

DTC_DEFINE(eDTCIDAngleSenOutUnderVol,eDTCFunCom_AngleSenOutUnderVol, 0xE4,0x6E0,1,1,1)

DTC_DEFINE(eDTCIDMotorHallPowOverVol,eDTCFunCom_MotorHallPowOverVol, 0xE3,0x7E0,1,1,1)

DTC_DEFINE(eDTCIDMotorHallPowUnderVol,eDTCFunCom_MotorHallPowUnderVol, 0xE4,0x7E0,1,1,1)

DTC_DEFINE(eDTCIDMotorHallOutNumError,eDTCFunCom_MotorHallOutNumError, 0xE2,0x8E0,1,1,1)

DTC_DEFINE(eDTCIDMotorHallOutOrderError,eDTCFunCom_MotorHallOutOrderError, 0xE8,0x8E0,1,1,1)

DTC_DEFINE(eDTCIDMotorPhaseOverCur,eDTCFunCom_MotorPhaseOverCur, 0xE6,0x9E0,1,1,1)

DTC_DEFINE(eDTCIDMotorOpenOrShortGnd,eDTCFunCom_MotorOpenOrShortGnd, 0xE5,0x9E0,1,1,1)

DTC_DEFINE(eDTCIDMotorShortPhase,eDTCFunCom_MotorShortPhase, 0xE0,0x9E0,1,1,1)

DTC_DEFINE(eDTCIDMotorOverCurLocked,eDTCFunCom_MotorOverCurLocked, 0xF0,0x9E0,1,1,1)

DTC_DEFINE(eDTCIDMotorShortPowOrPassive,eDTCFunCom_MotorShortPowOrPassive, 0xE3,0x9E0,1,1,1)

DTC_DEFINE(eDTCIDMotorBeyondVol,eDTCFunCom_MotorBeyondVol, 0xE2,0x9E0,1,1,1)

DTC_DEFINE(eDTCIDMotorDrvOverTemp,eDTCFunCom_MotorDrvOverTemp, 0xF6,0xAE0,1,1,1)

DTC_DEFINE(eDTCIDMotorDrvOverVol,eDTCFunCom_MotorDrvOverVol, 0xE3,0xAE0,1,1,1)

DTC_DEFINE(eDTCIDMotorDrvUnderVol,eDTCFunCom_MotorDrvUnderVol, 0xE4,0xAE0,1,1,1)

DTC_DEFINE(eDTCIDMOSOverCur,eDTCFunCom_MOSOverCur, 0xE6,0xAE0,1,1,1)

DTC_DEFINE(eDTCIDMOSShootThrough,eDTCFunCom_MOSShootThrough, 0xF7,0xAE0,1,1,1)

DTC_DEFINE(eDTCIDMotorBrakeShortGnd,eDTCFunCom_MotorBrakeShortGnd, 0xE6,0xCE0,1,1,1)

DTC_DEFINE(eDTCIDMotorBrakeOpen,eDTCFunCom_MotorBrakeOpen, 0xE5,0xCE0,1,1,1)

DTC_DEFINE(eDTCIDMotorBrakeShortPow,eDTCFunCom_MotorBrakeShortPow, 0xE3,0xCE0,1,1,1)

DTC_DEFINE(eDTCIDCanFault,eDTCFunCom_CanFault, 0xF3,0x12E0,1,1,1)

DTC_DEFINE(eDTCIDEEPFault,eDTCFunCom_EEPFault, 0xEB,0x15E0,1,1,1)

DTC_DEFINE(eDTCIDBatOverVol,eDTCFunCom_BatOverVol, 0xE3,0x22E0,1,1,1)

DTC_DEFINE(eDTCIDBatUnderVol,eDTCFunCom_BatUnderVol, 0xE4,0x22E0,1,1,1)

DTC_DEFINE(eDTCIDReserve1ShortGnd,eDTCFunCom_Reserve1ShortGnd, 0xE6,0xDE0,1,1,1)

DTC_DEFINE(eDTCIDReserve1Open,eDTCFunCom_Reserve1Open, 0xE5,0xDE0,1,1,1)

DTC_DEFINE(eDTCIDReserve1ShortPow,eDTCFunCom_Reserve1ShortPow, 0xE3,0xDE0,1,1,1)

DTC_DEFINE(eDTCIDDoorLampShortGnd,eDTCFunCom_DoorLampShortGnd, 0xE6,0xEE0,1,1,1)

DTC_DEFINE(eDTCIDDoorLampOpen,eDTCFunCom_DoorLampOpen, 0xE5,0xEE0,1,1,1)

DTC_DEFINE(eDTCIDDoorLampShortPow,eDTCFunCom_DoorLampShortPow, 0xE3,0xEE0,1,1,1)

DTC_DEFINE(eDTCIDReserve2ShortGnd,eDTCFunCom_Reserve2ShortGnd, 0xE6,0xFE0,1,1,1)

DTC_DEFINE(eDTCIDReserve2Open,eDTCFunCom_Reserve2Open, 0xE5,0xFE0,1,1,1)


#undef DTC_DEFINE
