//This file was generated by DAT_DTC_CFG.xlsm
#ifndef SOURCE_PLFICU_DAT_DAT_DTC_DAT_DTC_EFUNCOM_H_
#define SOURCE_PLFICU_DAT_DAT_DTC_DAT_DTC_EFUNCOM_H_

typedef enum
{
    eDTCFunCom_AngleSenPowOverVol = 0U,
    eDTCFunCom_AngleSenPowUnderVol,
    eDTCFunCom_AngleSenOutFault,
    eDTCFunCom_AngleSenOutOverVol,
    eDTCFunCom_AngleSenOutUnderVol,
    eDTCFunCom_MotorHallPowOverVol,
    eDTCFunCom_MotorHallPowUnderVol,
    eDTCFunCom_MotorHallOutNumError,
    eDTCFunCom_MotorHallOutOrderError,
    eDTCFunCom_MotorPhaseOverCur,
    eDTCFunCom_MotorOpenOrShortGnd,
    eDTCFunCom_MotorShortPhase,
    eDTCFunCom_MotorOverCurLocked,
    eDTCFunCom_MotorShortPowOrPassive,
    eDTCFunCom_MotorBeyondVol,
    eDTCFunCom_MotorDrvOverTemp,
    eDTCFunCom_MotorDrvOverVol,
    eDTCFunCom_MotorDrvUnderVol,
    eDTCFunCom_MOSOverCur,
    eDTCFunCom_MOSShootThrough,
    eDTCFunCom_MotorBrakeShortGnd,
    eDTCFunCom_MotorBrakeOpen,
    eDTCFunCom_MotorBrakeShortPow,
    eDTCFunCom_CanFault,
    eDTCFunCom_EEPFault,
    eDTCFunCom_BatOverVol,
    eDTCFunCom_BatUnderVol,
    eDTCFunCom_Reserve1ShortGnd,
    eDTCFunCom_Reserve1Open,
    eDTCFunCom_Reserve1ShortPow,
    eDTCFunCom_DoorLampShortGnd,
    eDTCFunCom_DoorLampOpen,
    eDTCFunCom_DoorLampShortPow,
    eDTCFunCom_Reserve2ShortGnd,
    eDTCFunCom_Reserve2Open,
    eDTCFunCom_Count
} tDTCFunCom;

#endif
