
import sys
import os
import time
import getpass
import shutil
import glob
import re

'''
将其中的11位ID值换成真正的29位ID值
#define cDATCdlIdentTxDiagOnCanPAP      ((tAddress)0x600UL)
#define cDATCdlIdentTxDiagOnCanDiffusion      ((tAddress)0x998UL)
#define cDATCdlIdentTxTX_CAN1_LocalTime_0x18FEE617_Proxy_0x180      ((tAddress)0x18FEE617UL)
#define cDATCdlIdentTxTX_CAN1_Mile_0x18FEC117_Proxy_0x281      ((tAddress)0x18FEC117UL)
'''


gStrCAN_MSG_CFGFilePath = r".\..\..\..\XXX\YYY\DAT\DAT_CAN\CAN_MSG_CFG.jil"
gStrDATCDLpFilePath = r".\..\..\..\XXX\YYY\SCC2Gen\GEN\DAT_CDLp.h"
gStrDATCPLTableTimeoutHFilePath = r".\..\..\..\XXX\YYY\DAT\DAT_CAN\DAT_CPL\DAT_CPL_TableTimeout.h"

gRegNormalMsg=r"#define\s+cDATCdlIdentTxTX_CAN\d_\w+?_0x(\w+?)_Proxy_0x\w+?\s{1,}\(\(tAddress\)0x(\w+UL)\)"
gRegSubID = r"\(\(tAddress\)0x(\w+)UL\)"
gRegP2P = r"cDATCdlIdentTxDiagOnCanPAP\s+\(\(tAddress\)0x(\d+)UL\)"
gRegDiffusion=r"cDATCdlIdentTxDiagOnCanDiffusion\s+\(\(tAddress\)0x(\d+)UL\)"
gRegRXHandle = r"#define\s{1,}cDATCdlD_UURxHandle(\w+)\s{1,}\(\(tDATCdlD_UURxHandle\)(\d{1,})\)"
gRxCBKDemo = r"{CallBackReceptionMsgName, ((tAddress)0xFFFFFFFFUL)}"
gRxCBKFuncHeader = """#define mDATCdlDefRxSpontTable()  \\
const tRxSpontWithAddr DATCanRxSpontTable[] = \\
{"""


gRegTime = r"CANUUDTMessage\s*UUDT_(RX_\w+)\n\s*{\n.*\n.*\n.*\n.*\n.*\n\s*TimeoutMs\s*=\s*(\d+)"

gListRxHandle = []
gListTime = []
gStrTable = ""


def GetRxHandle():

    global gListRxHandle

    if os.path.exists(gStrDATCDLpFilePath):
        #fMsg2Hadnle = open("Msg2Handle.txt","w")
        fHandle = open(gStrDATCDLpFilePath,"r")
        strFileContent = fHandle.read()
        #查找每个接收消息的句柄
        gListRxHandle = re.findall(gRegRXHandle,strFileContent,re.S)
        #print gListRxHandle
    else:
        print "Not find DAT_CDLp.h , please check"



def GetTimeoutMs():
    global gListTime

    if os.path.exists(gStrCAN_MSG_CFGFilePath):
        #fMsg2Hadnle = open("Msg2Handle.txt","w")
        fHandle = open(gStrCAN_MSG_CFGFilePath,"r")
        strFileContent = fHandle.read()

        gListTime = re.findall(gRegTime,strFileContent)
        #print gListTime

        fHandle.close()

    else:
        print "Not find CAN_MSG_CFG.jil , please check"

def CreatTable():
    global gStrTable

    for Index in range(len(gListRxHandle)):

        if gListRxHandle[Index][0][0] == "T":
            gStrTable = gStrTable + "    5000" +", //Handle  " + str(Index) + "\n"
        else:
            FindFlag = 0
            for each in gListTime:

                if gListRxHandle[Index][0] == each[0]:
                    gStrTable = gStrTable + " "*4 + each[1] +", //Handle  " + str(Index) + "\n"

                    FindFlag = 1
                    break;
            if FindFlag == 0:
                print "error: Can not find " + gListRxHandle[Index][0] + " in " + gStrCAN_MSG_CFGFilePath
                return
    #print gStrTable

    fHandle = open(gStrDATCPLTableTimeoutHFilePath,"w+")
    fHandle.write("//This file is auto generated by CanTimeout.exe \n\n")
    fHandle.write("#ifndef SOURCE_PLFICU_DAT_DAT_CAN_DAT_CPL_DAT_CPL_TABLETIMEOUT_H_\n#define SOURCE_PLFICU_DAT_DAT_CAN_DAT_CPL_DAT_CPL_TABLETIMEOUT_H_\n\n")
    fHandle.write("const U32 cau32DATCplTableTimeoutMs[cDATCdl_NbUURx] =\n{\n")
    fHandle.write(gStrTable)
    fHandle.write("};\n\n\n#endif /* SOURCE_PLFICU_DAT_DAT_CAN_DAT_CPL_DAT_CPL_TABLETIMEOUT_H_ */\n")


    fHandle.close()

'''
1.00
    Create this tool,生成接收报文超时时间数组

'''
def PrintVersion():
    strVersion = "1.00"
    print "%s version is %s"%(os.path.basename(sys.argv[0]),strVersion)

#将\XXX\YYY替换为真正的路径
def SubRealSourcePath(strSub):
    strReg = r".+(\\\w+\\\w+)\\LAP\\LAP_SUP"
    regXY = r"\\XXX\\YYY"
    for root,dirs,files in os.walk(r".\..\..\.."):#搜索当前路径
        for Each in files:
            if Each == "LAP_SUP.c": #找到LAP_SUP.c，将LAP文件夹前面两层路径提取出来
                listRealPath = re.findall(strReg,root)

                strRealPath = re.sub(regXY,listRealPath[0],strSub)#将\XXX\YYY替换为真正的路径

                return strRealPath


if __name__ == '__main__':

    gStrCAN_MSG_CFGFilePath = SubRealSourcePath(gStrCAN_MSG_CFGFilePath)
    gStrDATCDLpFilePath = SubRealSourcePath(gStrDATCDLpFilePath)
    gStrDATCPLTableTimeoutHFilePath = SubRealSourcePath(gStrDATCPLTableTimeoutHFilePath)

    PrintVersion()
    GetRxHandle()
    GetTimeoutMs()
    CreatTable()

##    fHandle = open(gStrRxSpontTableHFilePath,"w")
##    fHandle.write( GetRxMsgName())
##    fHandle.close()