//This file is auto generated by AutoGenEEPInit.exe

#ifndef I_DAT_PEE_INIT_GEN_H
#define I_DAT_PEE_INIT_GEN_H

#define mSBKGroupsRebuild()                                                           \
		case cDATSbkHandleErrorGroup:                \
			mSetSbkDefaultValue(ErrorGroup);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupTraceability:                \
			mSetSbkDefaultValue(GroupTraceability);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupPlantTraceability:                \
			mSetSbkDefaultValue(GroupPlantTraceability);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupDiagReserved:                \
			mSetSbkDefaultValue(GroupDiagReserved);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupPlantCalibiration:                \
			mSetSbkDefaultValue(GroupPlantCalibiration);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupReset:                \
			mSetSbkDefaultValue(GroupReset);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupSbkReadOnly1:                \
			mSetSbkDefaultValue(GroupSbkReadOnly1);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupSbkReadOnly2:                \
			mSetSbkDefaultValue(GroupSbkReadOnly2);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupBCMCfg0:                \
			mSetSbkDefaultValue(GroupBCMCfg0);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupBCMCfg1:                \
			mSetSbkDefaultValue(GroupBCMCfg1);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupBCMCfg2:                \
			mSetSbkDefaultValue(GroupBCMCfg2);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupBCMCfg3:                \
			mSetSbkDefaultValue(GroupBCMCfg3);         \
			break;                                  \
                                                    \
                                                    \
		case cDATSbkHandleGroupEEPInitCtrl:                \
			mSetSbkDefaultValue(GroupEEPInitCtrl);         \
			break;                                  \
                                                    \




#define mDBKGroupsRebuild()                                                           \
                                                   \
    case cDATDbkHandleGroupSTKDTC:                   \
		mSetDbkDefaultValue(GroupSTKDTC);            \
      break;                                       \
                                                   \
                                                    \
                                                   \
    case cDATDbkHandleGroupDTC:                   \
		mSetDbkDefaultValue(GroupDTC);            \
      break;                                       \
                                                   \
                                                    \
                                                   \
    case cDATDbkHandleGroupDIUpperLimit:                   \
		mSetDbkDefaultValue(GroupDIUpperLimit);            \
      break;                                       \
                                                   \
                                                    \
                                                   \
    case cDATDbkHandleGroupDILowerLimit:                   \
		mSetDbkDefaultValue(GroupDILowerLimit);            \
      break;                                       \
                                                   \
                                                    \
                                                   \
    case cDATDbkHandleGroupDIType:                   \
		mSetDbkDefaultValue(GroupDIType);            \
      break;                                       \
                                                   \
                                                    \
                                                   \
    case cDATDbkHandleGroupSensorCal:                   \
		mSetDbkDefaultValue(GroupSensorCal);            \
      break;                                       \
                                                   \
                                                    \
                                                   \
    case cDATDbkHandleGroupSensorCal1:                   \
		mSetDbkDefaultValue(GroupSensorCal1);            \
      break;                                       \
                                                   \
                                                    \
                                                   \
    case cDATDbkHandleGroupSensorCal2:                   \
		mSetDbkDefaultValue(GroupSensorCal2);            \
      break;                                       \
                                                   \


#endif
