//This file is auto generated by AutoGenHALChannels.exe


//------------------------------------------------------------------------------
// Body Identification
//------------------------------------------------------------------------------

#define HAL   "HAL"

//------------------------------------------------------------------------------
// Included files to resolve specific definitions in this file
//
// #include <system_file_name.h>
// #include "project_file_name.h"
//------------------------------------------------------------------------------
#include "HAL.h"

//------------------------------------------------------------------------------
// Local constants
//
// #define cConstantName   ((tType) ConstantValue)
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Local macros
//
// #define mMacroName   (MacroDefinition)
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Local types
//
// typedef Expression    tTypeName;
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Data prefix
//
// unsigned int {u8,u16,u32} / signed int {s8,s16,s32} 
// register size unsigned int {r} / float {f32,f64}  / s for struct 
//
// -----------------------------------------------------------------------------
// Local data
//
// static  tType   u8VariableName;  
// static  tType*  pu8VariableName; 
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Constant local data
//
// static const tType  VariableName;
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Exported data
//
// tType   u8LAYCmpVariableName; (LAY: 3 characters to identify the layer)
// tType*  pu8LAYCmpVariableName;(Cmp: 3 characters to identify the component)
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Constant exported data
//
//             (LAY: 3 characters to identify the layer)
//             (Cmp: 3 characters to identify this component)
// 
// const tType   LAYCmpVariableName;
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Local function prototypes
// 
// static tTypeRetour FunctionName(tTypeArgument1 ArgumentName1, ... );
//------------------------------------------------------------------------------

//==============================================================================
//=========================== LOCAL FUNCTIONS ==================================
//==============================================================================

//==============================================================================
//=========================== EXPORTED FUNCTIONS ===============================
//==============================================================================

//==============================================================================
// DESCRIPTION : Init of the LDB layer
//
// PARAMETERS (Type,Name,Min,Max) :   none
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBInit(void)
{
    LDBSupPreInit();

	
#ifdef mLDBSUPInit
    mLDBSUPInit();
#endif

#ifdef mLDBDINInit
    mLDBDINInit();
#endif

#ifdef mLDBBLDCInit
    mLDBBLDCInit();
#endif

#ifdef mLDBINTInit
    mLDBINTInit();
#endif

#ifdef mLDBDOUInit
    mLDBDOUInit();
#endif

#ifdef mLDBTIMInit
    mLDBTIMInit();
#endif

#ifdef mLDBPWMInit
    mLDBPWMInit();
#endif

#ifdef mLDBEEPInit
    mLDBEEPInit();
#endif

#ifdef mLDBRSTInit
    mLDBRSTInit();
#endif

#ifdef mLDBADInit
    mLDBADInit();
#endif

#ifdef mLDBICUInit
    mLDBICUInit();
#endif

#ifdef mLDBBSDCInit
    mLDBBSDCInit();
#endif

#ifdef mLDBCan0Init
    mLDBCan0Init();
#endif

#ifdef mLDBCan1Init
    mLDBCan1Init();
#endif

#ifdef mLDBCan2Init
    mLDBCan2Init();
#endif


	LDBSupEndInit();
}

//==============================================================================
// DESCRIPTION : enter in sleep mode
//
// PARAMETERS (Type,Name,Min,Max) :   none
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBEnterSleepMode(void)
{
  
#ifdef mLDBSUPEnterSleepMode
    mLDBSUPEnterSleepMode();
#endif

#ifdef mLDBDINEnterSleepMode
    mLDBDINEnterSleepMode();
#endif

#ifdef mLDBBLDCEnterSleepMode
    mLDBBLDCEnterSleepMode();
#endif

#ifdef mLDBINTEnterSleepMode
    mLDBINTEnterSleepMode();
#endif

#ifdef mLDBDOUEnterSleepMode
    mLDBDOUEnterSleepMode();
#endif

#ifdef mLDBTIMEnterSleepMode
    mLDBTIMEnterSleepMode();
#endif

#ifdef mLDBPWMEnterSleepMode
    mLDBPWMEnterSleepMode();
#endif

#ifdef mLDBEEPEnterSleepMode
    mLDBEEPEnterSleepMode();
#endif

#ifdef mLDBRSTEnterSleepMode
    mLDBRSTEnterSleepMode();
#endif

#ifdef mLDBADEnterSleepMode
    mLDBADEnterSleepMode();
#endif

#ifdef mLDBICUEnterSleepMode
    mLDBICUEnterSleepMode();
#endif

#ifdef mLDBBSDCEnterSleepMode
    mLDBBSDCEnterSleepMode();
#endif

#ifdef mLDBCan0EnterSleepMode
    mLDBCan0EnterSleepMode();
#endif

#ifdef mLDBCan1EnterSleepMode
    mLDBCan1EnterSleepMode();
#endif

#ifdef mLDBCan2EnterSleepMode
    mLDBCan2EnterSleepMode();
#endif

  LDBSupEnterSleepMode();
}

//==============================================================================
// DESCRIPTION : Leave sleep mode
//
// PARAMETERS (Type,Name,Min,Max) :   none
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBLeaveSleepMode(void)
{
  LDBSupLeaveSleepMode();
  
#ifdef mLDBSUPLeaveSleepMode
    mLDBSUPLeaveSleepMode();
#endif

#ifdef mLDBDINLeaveSleepMode
    mLDBDINLeaveSleepMode();
#endif

#ifdef mLDBBLDCLeaveSleepMode
    mLDBBLDCLeaveSleepMode();
#endif

#ifdef mLDBINTLeaveSleepMode
    mLDBINTLeaveSleepMode();
#endif

#ifdef mLDBDOULeaveSleepMode
    mLDBDOULeaveSleepMode();
#endif

#ifdef mLDBTIMLeaveSleepMode
    mLDBTIMLeaveSleepMode();
#endif

#ifdef mLDBPWMLeaveSleepMode
    mLDBPWMLeaveSleepMode();
#endif

#ifdef mLDBEEPLeaveSleepMode
    mLDBEEPLeaveSleepMode();
#endif

#ifdef mLDBRSTLeaveSleepMode
    mLDBRSTLeaveSleepMode();
#endif

#ifdef mLDBADLeaveSleepMode
    mLDBADLeaveSleepMode();
#endif

#ifdef mLDBICULeaveSleepMode
    mLDBICULeaveSleepMode();
#endif

#ifdef mLDBBSDCLeaveSleepMode
    mLDBBSDCLeaveSleepMode();
#endif

#ifdef mLDBCan0LeaveSleepMode
    mLDBCan0LeaveSleepMode();
#endif

#ifdef mLDBCan1LeaveSleepMode
    mLDBCan1LeaveSleepMode();
#endif

#ifdef mLDBCan2LeaveSleepMode
    mLDBCan2LeaveSleepMode();
#endif

}


//==============================================================================
// DESCRIPTION : Switching of the send with address access
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - Addr: Start address of the data to write
//      - *pMsg: datas buffer
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBSendWithAddr (tChannel Channel, tAddress Addr, tMsg *pMsg )
{
    switch (Channel)
    {
	
	
#ifdef mLDBSUPSendWithAddr
    case cLDBChannelLDB_SUP:
        mLDBSUPSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBDINSendWithAddr
    case cLDBChannelLDB_DIN:
        mLDBDINSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBBLDCSendWithAddr
    case cLDBChannelLDB_BLDC:
        mLDBBLDCSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBINTSendWithAddr
    case cLDBChannelLDB_INT:
        mLDBINTSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBDOUSendWithAddr
    case cLDBChannelLDB_DOU:
        mLDBDOUSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBTIMSendWithAddr
    case cLDBChannelLDB_TIM:
        mLDBTIMSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBPWMSendWithAddr
    case cLDBChannelLDB_PWM:
        mLDBPWMSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBEEPSendWithAddr
    case cLDBChannelLDB_EEP:
        mLDBEEPSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBRSTSendWithAddr
    case cLDBChannelLDB_RST:
        mLDBRSTSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBADSendWithAddr
    case cLDBChannelLDB_AD:
        mLDBADSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBICUSendWithAddr
    case cLDBChannelLDB_ICU:
        mLDBICUSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBBSDCSendWithAddr
    case cLDBChannelLDB_BSDC:
        mLDBBSDCSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBCan0SendWithAddr
    case cLDBChannelCan0:
        mLDBCan0SendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBCan1SendWithAddr
    case cLDBChannelCan1:
        mLDBCan1SendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBCan2SendWithAddr
    case cLDBChannelCan2:
        mLDBCan2SendWithAddr(Addr,pMsg);
    break;
#endif

	
    default :
        mLIBassert(cFalse);
        break;
    }
}

//==============================================================================
// DESCRIPTION : Switching of the prepare to send with address access
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - Addr: Start address of the data to write
//      - *pMsg: datas buffer
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBPrepareSendWithAddr (tChannel Channel, tAddress Addr, tMsg *pMsg )
{
    switch (Channel)
    {
	
	
#ifdef mLDBSUPPrepareSendWithAddr
    case cLDBChannelLDB_SUP:
        mLDBSUPPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBDINPrepareSendWithAddr
    case cLDBChannelLDB_DIN:
        mLDBDINPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBBLDCPrepareSendWithAddr
    case cLDBChannelLDB_BLDC:
        mLDBBLDCPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBINTPrepareSendWithAddr
    case cLDBChannelLDB_INT:
        mLDBINTPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBDOUPrepareSendWithAddr
    case cLDBChannelLDB_DOU:
        mLDBDOUPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBTIMPrepareSendWithAddr
    case cLDBChannelLDB_TIM:
        mLDBTIMPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBPWMPrepareSendWithAddr
    case cLDBChannelLDB_PWM:
        mLDBPWMPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBEEPPrepareSendWithAddr
    case cLDBChannelLDB_EEP:
        mLDBEEPPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBRSTPrepareSendWithAddr
    case cLDBChannelLDB_RST:
        mLDBRSTPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBADPrepareSendWithAddr
    case cLDBChannelLDB_AD:
        mLDBADPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBICUPrepareSendWithAddr
    case cLDBChannelLDB_ICU:
        mLDBICUPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBBSDCPrepareSendWithAddr
    case cLDBChannelLDB_BSDC:
        mLDBBSDCPrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBCan0PrepareSendWithAddr
    case cLDBChannelCan0:
        mLDBCan0PrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBCan1PrepareSendWithAddr
    case cLDBChannelCan1:
        mLDBCan1PrepareSendWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBCan2PrepareSendWithAddr
    case cLDBChannelCan2:
        mLDBCan2PrepareSendWithAddr(Addr,pMsg);
    break;
#endif

	
    default :
        mLIBassert(cFalse);
        break;
    }
}

//==============================================================================
// DESCRIPTION : Switching of the send without address access
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - *pMsg: datas buffer
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBSendWithoutAddr (tChannel Channel, tMsg *pMsg )
{
    switch (Channel)
    {
	
	
#ifdef mLDBSUPSendWithoutAddr
    case cLDBChannelLDB_SUP:
        mLDBSUPSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBDINSendWithoutAddr
    case cLDBChannelLDB_DIN:
        mLDBDINSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBBLDCSendWithoutAddr
    case cLDBChannelLDB_BLDC:
        mLDBBLDCSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBINTSendWithoutAddr
    case cLDBChannelLDB_INT:
        mLDBINTSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBDOUSendWithoutAddr
    case cLDBChannelLDB_DOU:
        mLDBDOUSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBTIMSendWithoutAddr
    case cLDBChannelLDB_TIM:
        mLDBTIMSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBPWMSendWithoutAddr
    case cLDBChannelLDB_PWM:
        mLDBPWMSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBEEPSendWithoutAddr
    case cLDBChannelLDB_EEP:
        mLDBEEPSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBRSTSendWithoutAddr
    case cLDBChannelLDB_RST:
        mLDBRSTSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBADSendWithoutAddr
    case cLDBChannelLDB_AD:
        mLDBADSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBICUSendWithoutAddr
    case cLDBChannelLDB_ICU:
        mLDBICUSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBBSDCSendWithoutAddr
    case cLDBChannelLDB_BSDC:
        mLDBBSDCSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBCan0SendWithoutAddr
    case cLDBChannelCan0:
        mLDBCan0SendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBCan1SendWithoutAddr
    case cLDBChannelCan1:
        mLDBCan1SendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBCan2SendWithoutAddr
    case cLDBChannelCan2:
        mLDBCan2SendWithoutAddr(pMsg);
    break;
#endif

	
    default :
        mLIBassert(cFalse);
        break;
    }
}

//==============================================================================
// DESCRIPTION : Switching of the prepare to send without address access
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - *pMsg: datas buffer
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBPrepareSendWithoutAddr(tChannel Channel, tMsg* pMsg)
{
    switch (Channel)
    {
		
	
#ifdef mLDBSUPPrepareSendWithoutAddr
    case cLDBChannelLDB_SUP:
        mLDBSUPPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBDINPrepareSendWithoutAddr
    case cLDBChannelLDB_DIN:
        mLDBDINPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBBLDCPrepareSendWithoutAddr
    case cLDBChannelLDB_BLDC:
        mLDBBLDCPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBINTPrepareSendWithoutAddr
    case cLDBChannelLDB_INT:
        mLDBINTPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBDOUPrepareSendWithoutAddr
    case cLDBChannelLDB_DOU:
        mLDBDOUPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBTIMPrepareSendWithoutAddr
    case cLDBChannelLDB_TIM:
        mLDBTIMPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBPWMPrepareSendWithoutAddr
    case cLDBChannelLDB_PWM:
        mLDBPWMPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBEEPPrepareSendWithoutAddr
    case cLDBChannelLDB_EEP:
        mLDBEEPPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBRSTPrepareSendWithoutAddr
    case cLDBChannelLDB_RST:
        mLDBRSTPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBADPrepareSendWithoutAddr
    case cLDBChannelLDB_AD:
        mLDBADPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBICUPrepareSendWithoutAddr
    case cLDBChannelLDB_ICU:
        mLDBICUPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBBSDCPrepareSendWithoutAddr
    case cLDBChannelLDB_BSDC:
        mLDBBSDCPrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBCan0PrepareSendWithoutAddr
    case cLDBChannelCan0:
        mLDBCan0PrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBCan1PrepareSendWithoutAddr
    case cLDBChannelCan1:
        mLDBCan1PrepareSendWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBCan2PrepareSendWithoutAddr
    case cLDBChannelCan2:
        mLDBCan2PrepareSendWithoutAddr(pMsg);
    break;
#endif

	
    default :
        mLIBassert(cFalse);
        break;
    }
}

//==============================================================================
// DESCRIPTION : Switching of the received with address access
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - Addr: Start address of the data to write
//      - *pMsg: datas buffer
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBReceiveWithAddr(tChannel Channel, tAddress Addr, tMsg *pMsg)
{
    switch (Channel)
    {

	
#ifdef mLDBSUPReceiveWithAddr
    case cLDBChannelLDB_SUP:
        mLDBSUPReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBDINReceiveWithAddr
    case cLDBChannelLDB_DIN:
        mLDBDINReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBBLDCReceiveWithAddr
    case cLDBChannelLDB_BLDC:
        mLDBBLDCReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBINTReceiveWithAddr
    case cLDBChannelLDB_INT:
        mLDBINTReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBDOUReceiveWithAddr
    case cLDBChannelLDB_DOU:
        mLDBDOUReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBTIMReceiveWithAddr
    case cLDBChannelLDB_TIM:
        mLDBTIMReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBPWMReceiveWithAddr
    case cLDBChannelLDB_PWM:
        mLDBPWMReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBEEPReceiveWithAddr
    case cLDBChannelLDB_EEP:
        mLDBEEPReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBRSTReceiveWithAddr
    case cLDBChannelLDB_RST:
        mLDBRSTReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBADReceiveWithAddr
    case cLDBChannelLDB_AD:
        mLDBADReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBICUReceiveWithAddr
    case cLDBChannelLDB_ICU:
        mLDBICUReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBBSDCReceiveWithAddr
    case cLDBChannelLDB_BSDC:
        mLDBBSDCReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBCan0ReceiveWithAddr
    case cLDBChannelCan0:
        mLDBCan0ReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBCan1ReceiveWithAddr
    case cLDBChannelCan1:
        mLDBCan1ReceiveWithAddr(Addr,pMsg);
    break;
#endif

#ifdef mLDBCan2ReceiveWithAddr
    case cLDBChannelCan2:
        mLDBCan2ReceiveWithAddr(Addr,pMsg);
    break;
#endif

	
    default :
        mLIBassert(cFalse);
        break;
    }
}

//==============================================================================
// DESCRIPTION : Switching of the received without address access
//
// PARAMETERS (Type,Name,Min,Max) :   none
//      - Channel: Channel identifier
//      - *pMsg: datas buffer
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBReceiveWithoutAddr(tChannel Channel, tMsg *pMsg)
{
    switch (Channel)
    {

	
#ifdef mLDBSUPReceiveWithoutAddr
    case cLDBChannelLDB_SUP:
        mLDBSUPReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBDINReceiveWithoutAddr
    case cLDBChannelLDB_DIN:
        mLDBDINReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBBLDCReceiveWithoutAddr
    case cLDBChannelLDB_BLDC:
        mLDBBLDCReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBINTReceiveWithoutAddr
    case cLDBChannelLDB_INT:
        mLDBINTReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBDOUReceiveWithoutAddr
    case cLDBChannelLDB_DOU:
        mLDBDOUReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBTIMReceiveWithoutAddr
    case cLDBChannelLDB_TIM:
        mLDBTIMReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBPWMReceiveWithoutAddr
    case cLDBChannelLDB_PWM:
        mLDBPWMReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBEEPReceiveWithoutAddr
    case cLDBChannelLDB_EEP:
        mLDBEEPReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBRSTReceiveWithoutAddr
    case cLDBChannelLDB_RST:
        mLDBRSTReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBADReceiveWithoutAddr
    case cLDBChannelLDB_AD:
        mLDBADReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBICUReceiveWithoutAddr
    case cLDBChannelLDB_ICU:
        mLDBICUReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBBSDCReceiveWithoutAddr
    case cLDBChannelLDB_BSDC:
        mLDBBSDCReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBCan0ReceiveWithoutAddr
    case cLDBChannelCan0:
        mLDBCan0ReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBCan1ReceiveWithoutAddr
    case cLDBChannelCan1:
        mLDBCan1ReceiveWithoutAddr(pMsg);
    break;
#endif

#ifdef mLDBCan2ReceiveWithoutAddr
    case cLDBChannelCan2:
        mLDBCan2ReceiveWithoutAddr(pMsg);
    break;
#endif

	
    default :
        mLIBassert(cFalse);
        break;
    }
}

//==============================================================================
// DESCRIPTION : Switching of the control access
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - Ctrl: Control type
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBControl (tChannel Channel, tCtrl Ctrl)
{
    switch (Channel)
    {

	
#ifdef mLDBSUPControl
    case cLDBChannelLDB_SUP:
        mLDBSUPControl(Ctrl);
    break;
#endif

#ifdef mLDBDINControl
    case cLDBChannelLDB_DIN:
        mLDBDINControl(Ctrl);
    break;
#endif

#ifdef mLDBBLDCControl
    case cLDBChannelLDB_BLDC:
        mLDBBLDCControl(Ctrl);
    break;
#endif

#ifdef mLDBINTControl
    case cLDBChannelLDB_INT:
        mLDBINTControl(Ctrl);
    break;
#endif

#ifdef mLDBDOUControl
    case cLDBChannelLDB_DOU:
        mLDBDOUControl(Ctrl);
    break;
#endif

#ifdef mLDBTIMControl
    case cLDBChannelLDB_TIM:
        mLDBTIMControl(Ctrl);
    break;
#endif

#ifdef mLDBPWMControl
    case cLDBChannelLDB_PWM:
        mLDBPWMControl(Ctrl);
    break;
#endif

#ifdef mLDBEEPControl
    case cLDBChannelLDB_EEP:
        mLDBEEPControl(Ctrl);
    break;
#endif

#ifdef mLDBRSTControl
    case cLDBChannelLDB_RST:
        mLDBRSTControl(Ctrl);
    break;
#endif

#ifdef mLDBADControl
    case cLDBChannelLDB_AD:
        mLDBADControl(Ctrl);
    break;
#endif

#ifdef mLDBICUControl
    case cLDBChannelLDB_ICU:
        mLDBICUControl(Ctrl);
    break;
#endif

#ifdef mLDBBSDCControl
    case cLDBChannelLDB_BSDC:
        mLDBBSDCControl(Ctrl);
    break;
#endif

#ifdef mLDBCan0Control
    case cLDBChannelCan0:
        mLDBCan0Control(Ctrl);
    break;
#endif

#ifdef mLDBCan1Control
    case cLDBChannelCan1:
        mLDBCan1Control(Ctrl);
    break;
#endif

#ifdef mLDBCan2Control
    case cLDBChannelCan2:
        mLDBCan2Control(Ctrl);
    break;
#endif


    default :
        mLIBassert(cFalse);
        break;
    }
}

//==============================================================================
// DESCRIPTION : Switching of the callback authorize access
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - CallBackAutorise: Ctrue or cFalse
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBEnableCallBack (tChannel Channel, BOOL CallBackAuthorize )
{
    switch (Channel)
    {

    
#ifdef mLDBSUPEnableCallBack
    case cLDBChannelLDB_SUP:
        mLDBSUPEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBDINEnableCallBack
    case cLDBChannelLDB_DIN:
        mLDBDINEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBBLDCEnableCallBack
    case cLDBChannelLDB_BLDC:
        mLDBBLDCEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBINTEnableCallBack
    case cLDBChannelLDB_INT:
        mLDBINTEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBDOUEnableCallBack
    case cLDBChannelLDB_DOU:
        mLDBDOUEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBTIMEnableCallBack
    case cLDBChannelLDB_TIM:
        mLDBTIMEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBPWMEnableCallBack
    case cLDBChannelLDB_PWM:
        mLDBPWMEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBEEPEnableCallBack
    case cLDBChannelLDB_EEP:
        mLDBEEPEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBRSTEnableCallBack
    case cLDBChannelLDB_RST:
        mLDBRSTEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBADEnableCallBack
    case cLDBChannelLDB_AD:
        mLDBADEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBICUEnableCallBack
    case cLDBChannelLDB_ICU:
        mLDBICUEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBBSDCEnableCallBack
    case cLDBChannelLDB_BSDC:
        mLDBBSDCEnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBCan0EnableCallBack
    case cLDBChannelCan0:
        mLDBCan0EnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBCan1EnableCallBack
    case cLDBChannelCan1:
        mLDBCan1EnableCallBack(CallBackAuthorize);
    break;
#endif

#ifdef mLDBCan2EnableCallBack
    case cLDBChannelCan2:
        mLDBCan2EnableCallBack(CallBackAuthorize);
    break;
#endif


    default :
        mLIBassert(cFalse);
        break;
    }
}


//==============================================================================
// DESCRIPTION : Switching of the callback for each channel
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - Ctrl: Control type
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBCallBackControl (tChannel Channel, tCtrl Ctrl, tStatus Status)
{
    switch (Channel)
    {

    
#ifdef mLDBSUPCallBackControl
    case cLDBChannelLDB_SUP:
        mLDBSUPCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBDINCallBackControl
    case cLDBChannelLDB_DIN:
        mLDBDINCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBBLDCCallBackControl
    case cLDBChannelLDB_BLDC:
        mLDBBLDCCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBINTCallBackControl
    case cLDBChannelLDB_INT:
        mLDBINTCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBDOUCallBackControl
    case cLDBChannelLDB_DOU:
        mLDBDOUCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBTIMCallBackControl
    case cLDBChannelLDB_TIM:
        mLDBTIMCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBPWMCallBackControl
    case cLDBChannelLDB_PWM:
        mLDBPWMCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBEEPCallBackControl
    case cLDBChannelLDB_EEP:
        mLDBEEPCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBRSTCallBackControl
    case cLDBChannelLDB_RST:
        mLDBRSTCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBADCallBackControl
    case cLDBChannelLDB_AD:
        mLDBADCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBICUCallBackControl
    case cLDBChannelLDB_ICU:
        mLDBICUCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBBSDCCallBackControl
    case cLDBChannelLDB_BSDC:
        mLDBBSDCCallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBCan0CallBackControl
    case cLDBChannelCan0:
        mLDBCan0CallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBCan1CallBackControl
    case cLDBChannelCan1:
        mLDBCan1CallBackControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBCan2CallBackControl
    case cLDBChannelCan2:
        mLDBCan2CallBackControl(Ctrl,Status);
    break;
#endif


    default :
        mLIBassert(cFalse);
        break;
    }
}

//==============================================================================
// DESCRIPTION : Switching of the callback end for each channel
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - Ctrl: Control type
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBCallBackEndControl (tChannel Channel, tCtrl Ctrl, tStatus Status)
{
    switch (Channel)
    {

    
#ifdef mLDBSUPCallBackEndControl
    case cLDBChannelLDB_SUP:
        mLDBSUPCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBDINCallBackEndControl
    case cLDBChannelLDB_DIN:
        mLDBDINCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBBLDCCallBackEndControl
    case cLDBChannelLDB_BLDC:
        mLDBBLDCCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBINTCallBackEndControl
    case cLDBChannelLDB_INT:
        mLDBINTCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBDOUCallBackEndControl
    case cLDBChannelLDB_DOU:
        mLDBDOUCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBTIMCallBackEndControl
    case cLDBChannelLDB_TIM:
        mLDBTIMCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBPWMCallBackEndControl
    case cLDBChannelLDB_PWM:
        mLDBPWMCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBEEPCallBackEndControl
    case cLDBChannelLDB_EEP:
        mLDBEEPCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBRSTCallBackEndControl
    case cLDBChannelLDB_RST:
        mLDBRSTCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBADCallBackEndControl
    case cLDBChannelLDB_AD:
        mLDBADCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBICUCallBackEndControl
    case cLDBChannelLDB_ICU:
        mLDBICUCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBBSDCCallBackEndControl
    case cLDBChannelLDB_BSDC:
        mLDBBSDCCallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBCan0CallBackEndControl
    case cLDBChannelCan0:
        mLDBCan0CallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBCan1CallBackEndControl
    case cLDBChannelCan1:
        mLDBCan1CallBackEndControl(Ctrl,Status);
    break;
#endif

#ifdef mLDBCan2CallBackEndControl
    case cLDBChannelCan2:
        mLDBCan2CallBackEndControl(Ctrl,Status);
    break;
#endif


    default :
        mLIBassert(cFalse);
        break;
    }
}
//==============================================================================
// DESCRIPTION : Switching of the callback for each channel,for Rx 
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - Ctrl: Control type
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBCallBackRxWithAddr (tChannel Channel, tAddress Addr, tStatus Status)
{
    switch (Channel)
    {

    
#ifdef mLDBSUPCallBackRxWithAddr
    case cLDBChannelLDB_SUP:
        mLDBSUPCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBDINCallBackRxWithAddr
    case cLDBChannelLDB_DIN:
        mLDBDINCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBBLDCCallBackRxWithAddr
    case cLDBChannelLDB_BLDC:
        mLDBBLDCCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBINTCallBackRxWithAddr
    case cLDBChannelLDB_INT:
        mLDBINTCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBDOUCallBackRxWithAddr
    case cLDBChannelLDB_DOU:
        mLDBDOUCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBTIMCallBackRxWithAddr
    case cLDBChannelLDB_TIM:
        mLDBTIMCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBPWMCallBackRxWithAddr
    case cLDBChannelLDB_PWM:
        mLDBPWMCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBEEPCallBackRxWithAddr
    case cLDBChannelLDB_EEP:
        mLDBEEPCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBRSTCallBackRxWithAddr
    case cLDBChannelLDB_RST:
        mLDBRSTCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBADCallBackRxWithAddr
    case cLDBChannelLDB_AD:
        mLDBADCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBICUCallBackRxWithAddr
    case cLDBChannelLDB_ICU:
        mLDBICUCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBBSDCCallBackRxWithAddr
    case cLDBChannelLDB_BSDC:
        mLDBBSDCCallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBCan0CallBackRxWithAddr
    case cLDBChannelCan0:
        mLDBCan0CallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBCan1CallBackRxWithAddr
    case cLDBChannelCan1:
        mLDBCan1CallBackRxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBCan2CallBackRxWithAddr
    case cLDBChannelCan2:
        mLDBCan2CallBackRxWithAddr(Addr,Status);
    break;
#endif


    default :
        mLIBassert(cFalse);
        break;
    }
}

//==============================================================================
// DESCRIPTION : Switching of the callback for each channel,for Tx
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - Ctrl: Control type
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBCallBackTxWithAddr (tChannel Channel, tAddress Addr, tStatus Status)
{
    switch (Channel)
    {

    
#ifdef mLDBSUPCallBackTxWithAddr
    case cLDBChannelLDB_SUP:
        mLDBSUPCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBDINCallBackTxWithAddr
    case cLDBChannelLDB_DIN:
        mLDBDINCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBBLDCCallBackTxWithAddr
    case cLDBChannelLDB_BLDC:
        mLDBBLDCCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBINTCallBackTxWithAddr
    case cLDBChannelLDB_INT:
        mLDBINTCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBDOUCallBackTxWithAddr
    case cLDBChannelLDB_DOU:
        mLDBDOUCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBTIMCallBackTxWithAddr
    case cLDBChannelLDB_TIM:
        mLDBTIMCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBPWMCallBackTxWithAddr
    case cLDBChannelLDB_PWM:
        mLDBPWMCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBEEPCallBackTxWithAddr
    case cLDBChannelLDB_EEP:
        mLDBEEPCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBRSTCallBackTxWithAddr
    case cLDBChannelLDB_RST:
        mLDBRSTCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBADCallBackTxWithAddr
    case cLDBChannelLDB_AD:
        mLDBADCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBICUCallBackTxWithAddr
    case cLDBChannelLDB_ICU:
        mLDBICUCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBBSDCCallBackTxWithAddr
    case cLDBChannelLDB_BSDC:
        mLDBBSDCCallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBCan0CallBackTxWithAddr
    case cLDBChannelCan0:
        mLDBCan0CallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBCan1CallBackTxWithAddr
    case cLDBChannelCan1:
        mLDBCan1CallBackTxWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBCan2CallBackTxWithAddr
    case cLDBChannelCan2:
        mLDBCan2CallBackTxWithAddr(Addr,Status);
    break;
#endif


    default :
        mLIBassert(cFalse);
        break;
    }
}


//==============================================================================
// DESCRIPTION : callback from Irq for each channel
//
// PARAMETERS (Type,Name,Min,Max) :
//      - Channel: Channel identifier
//      - Ctrl: Control type
//
// RETURN VALUE :   none
//
// DESIGN INFORMATION : (pseudo code, algorithm ... )
//==============================================================================
void LDBCallBackFromIrqWithAddr (tChannel Channel, tAddress Addr, tStatus Status)
{
    switch (Channel)
    {

    
#ifdef mLDBSUPCallBackFromIrqWithAddr
    case cLDBChannelLDB_SUP:
        mLDBSUPCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBDINCallBackFromIrqWithAddr
    case cLDBChannelLDB_DIN:
        mLDBDINCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBBLDCCallBackFromIrqWithAddr
    case cLDBChannelLDB_BLDC:
        mLDBBLDCCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBINTCallBackFromIrqWithAddr
    case cLDBChannelLDB_INT:
        mLDBINTCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBDOUCallBackFromIrqWithAddr
    case cLDBChannelLDB_DOU:
        mLDBDOUCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBTIMCallBackFromIrqWithAddr
    case cLDBChannelLDB_TIM:
        mLDBTIMCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBPWMCallBackFromIrqWithAddr
    case cLDBChannelLDB_PWM:
        mLDBPWMCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBEEPCallBackFromIrqWithAddr
    case cLDBChannelLDB_EEP:
        mLDBEEPCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBRSTCallBackFromIrqWithAddr
    case cLDBChannelLDB_RST:
        mLDBRSTCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBADCallBackFromIrqWithAddr
    case cLDBChannelLDB_AD:
        mLDBADCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBICUCallBackFromIrqWithAddr
    case cLDBChannelLDB_ICU:
        mLDBICUCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBBSDCCallBackFromIrqWithAddr
    case cLDBChannelLDB_BSDC:
        mLDBBSDCCallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBCan0CallBackFromIrqWithAddr
    case cLDBChannelCan0:
        mLDBCan0CallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBCan1CallBackFromIrqWithAddr
    case cLDBChannelCan1:
        mLDBCan1CallBackFromIrqWithAddr(Addr,Status);
    break;
#endif

#ifdef mLDBCan2CallBackFromIrqWithAddr
    case cLDBChannelCan2:
        mLDBCan2CallBackFromIrqWithAddr(Addr,Status);
    break;
#endif


    default :
        mLIBassert(cFalse);
        break;
    }
}




