//This file is auto generated by AutoGenHALChannels.exe
#ifndef I_HAL_INCLUDE_H
#define I_HAL_INCLUDE_H


#include "ARCH_CFG.h"

#ifdef cHeadIncludeType_Directly
#include "HAL_CHANNELS.h"
#else
#include "HAL_CHANNELS.h"
#endif


#ifdef cLDBChannelLDB_SUP
    #ifdef cHeadIncludeType_Directly
    #include "LDB_SUP.h"
    #else
    #include ".\..\LDB\LDB_SUP\LDB_SUP.h"
    #endif
#endif

#ifdef cLDBChannelLDB_DIN
    #ifdef cHeadIncludeType_Directly
    #include "LDB_DIN.h"
    #else
    #include ".\..\LDB\LDB_DIN\LDB_DIN.h"
    #endif
#endif

#ifdef cLDBChannelLDB_BLDC
    #ifdef cHeadIncludeType_Directly
    #include "LDB_BLDC.h"
    #else
    #include ".\..\LDB\LDB_BLDC\LDB_BLDC.h"
    #endif
#endif

#ifdef cLDBChannelLDB_INT
    #ifdef cHeadIncludeType_Directly
    #include "LDB_INT.h"
    #else
    #include ".\..\LDB\LDB_INT\LDB_INT.h"
    #endif
#endif

#ifdef cLDBChannelLDB_DOU
    #ifdef cHeadIncludeType_Directly
    #include "LDB_DOU.h"
    #else
    #include ".\..\LDB\LDB_DOU\LDB_DOU.h"
    #endif
#endif

#ifdef cLDBChannelLDB_TIM
    #ifdef cHeadIncludeType_Directly
    #include "LDB_TIM.h"
    #else
    #include ".\..\LDB\LDB_TIM\LDB_TIM.h"
    #endif
#endif

#ifdef cLDBChannelLDB_PWM
    #ifdef cHeadIncludeType_Directly
    #include "LDB_PWM.h"
    #else
    #include ".\..\LDB\LDB_PWM\LDB_PWM.h"
    #endif
#endif

#ifdef cLDBChannelLDB_EEP
    #ifdef cHeadIncludeType_Directly
    #include "LDB_EEP.h"
    #else
    #include ".\..\LDB\LDB_EEP\LDB_EEP.h"
    #endif
#endif

#ifdef cLDBChannelLDB_RST
    #ifdef cHeadIncludeType_Directly
    #include "LDB_RST.h"
    #else
    #include ".\..\LDB\LDB_RST\LDB_RST.h"
    #endif
#endif

#ifdef cLDBChannelLDB_AD
    #ifdef cHeadIncludeType_Directly
    #include "LDB_AD.h"
    #else
    #include ".\..\LDB\LDB_AD\LDB_AD.h"
    #endif
#endif

#ifdef cLDBChannelLDB_ICU
    #ifdef cHeadIncludeType_Directly
    #include "LDB_ICU.h"
    #else
    #include ".\..\LDB\LDB_ICU\LDB_ICU.h"
    #endif
#endif

#ifdef cLDBChannelLDB_BSDC
    #ifdef cHeadIncludeType_Directly
    #include "LDB_BSDC.h"
    #else
    #include ".\..\LDB\LDB_BSDC\LDB_BSDC.h"
    #endif
#endif

#if defined( cLDBChannelCan0) || defined( cLDBChannelCan1) || defined( cLDBChannelCan2)
    #ifdef cHeadIncludeType_Directly
    #include "LDB_CAN.h"
    #else
    #include ".\..\LDB\LDB_CAN\LDB_CAN.h"
    #endif
#endif
#endif
