//This file is auto generated by AutoGenHALChannels.exe
#ifndef I_HAL_CHANNELS_H
#define I_HAL_CHANNELS_H

#define cLDBChannelLDB_SUP    ((tChannel)1UL)
#define cLDBChannelLDB_DIN    ((tChannel)2UL)
#define cLDBChannelLDB_BLDC    ((tChannel)3UL)
#define cLDBChannelLDB_INT    ((tChannel)4UL)
#define cLDBChannelLDB_DOU    ((tChannel)5UL)
#define cLDBChannelLDB_TIM    ((tChannel)6UL)
#define cLDBChannelLDB_PWM    ((tChannel)7UL)
#define cLDBChannelLDB_EEP    ((tChannel)8UL)
#define cLDBChannelLDB_RST    ((tChannel)9UL)
#define cLDBChannelLDB_AD    ((tChannel)10UL)
#define cLDBChannelLDB_ICU    ((tChannel)11UL)
#define cLDBChannelLDB_BSDC    ((tChannel)12UL)
#define cLDBChannelCan0    ((tChannel)13UL)
#define cLDBChannelCan1    ((tChannel)14UL)
#define cLDBChannelCan2    ((tChannel)15UL)
#endif
