//This file is auto generated by AutoGenHALChannels.exe
#ifndef I_HAL_DATCBK_INCLUDE_H
#define I_HAL_DATCBK_INCLUDE_H


//#ifdef cSERChannelDAT_EEP
#ifdef cHeadIncludeType_Directly
#include "DAT_EEP_CBKEXPORT.h"
#else
#include ".\..\..\PLFICU\DAT\DAT_EEP\DAT_EEP_CBKEXPORT.h"
#endif
//#endif


//#ifdef cSERChannelDAT_DIN
#ifdef cHeadIncludeType_Directly
#include "DAT_DIN_CBKEXPORT.h"
#else
#include ".\..\..\PLFICU\DAT\DAT_DIO\DAT_DIN\DAT_DIN_CBKEXPORT.h"
#endif
//#endif

#endif
