# coding=utf-8
import sys
import os
import time
import getpass
import shutil
import glob
import re

gStrDATPath = r".\..\..\..\XXX\YYY\DAT\\"
gStrLAPPath = r".\..\..\..\XXX\YYY\LAP\\"
gStrSERINCLUDEPath = r".\..\..\..\XXX\YYY\SER\SER_INCLUDE\\"
gStrSCC2GenPath = r".\..\..\..\XXX\YYY\SCC2Gen\GEN\\"
gStrSubSource = "source"
gStrSubPLFICU = "PLFICU"

gStrDATExportFile = "DATAEXPORT.H"
gStrFuncExportFile = "FUNCEXPORT.H"
gStrTypeExportFile = "TYPEEXPORT.h"
gStrSERChLeading = 'cSERChannel'
gStrCHANNELSHHeader = '''#ifndef I_SER_CHANNELS_H
#define I_SER_CHANNELS_H


'''
gStrSERFUNCExpHeader1 ='''#ifndef I_SER_FUNCEXPORT_INCLUDE_H
#define I_SER_FUNCEXPORT_INCLUDE_H (1)
'''

gStrSERDATAExpHeader1 = '''#ifndef I_SER_DATAEXPORT_INCLUDE_H
#define I_SER_DATAEXPORT_INCLUDE_H (1)

'''

gStrSERTYPEExpHeaer1 = '''#ifndef I_SER_TYPEEXPORT_INCLUDE_H
#define I_SER_TYPEEXPORT_INCLUDE_H (1)

'''

gStrSERTYPEIncludeHeader = '''
#ifndef I_SER_TYPE_INCLUDE_H
#define I_SER_TYPE_INCLUDE_H (1)

'''


gStrSERExpHeader = '''
/*-------------------------------------------------------------------------
  Included files to resolve specific definitions in this file

  #include <system_file_name.h>
  #include "project_file_name.h"
  -------------------------------------------------------------------------*/
#include "ARCH_CFG.h"

#ifdef cHeadIncludeType_Directly
#include "SER_LIB.h"
#else
#include ".\..\SER_LIB.h"
#endif

//------------------------------------------------------------------------------
// Local constants
//------------------------------------------------------------------------------
'''

gStrSER_CHANNEL_H = r"SER_INCLUDE_h"
gStrSER_DATAExp_H = r"SER_DATAEXPORT_INCLUDE.h"
gStrSER_FUNCExp_H = r"SER_FUNCEXPORT_INCLUDE.h"
gStrSER_TYPEExp_H = r"SER_TYPEEXPORT_INCLUDE.h"

gDictDATDATAEXPORTPath = {}
gDictDATFUNCEXPORTPath = {}
gDictDATTYPEEXPORTPath = {}
gSetSERChlName =  set()
#remove the sub modle in special composed models
gDictSpecialDATHeader = {}#{"DAT_DIN":"DAT_DIO","DAT_DOU":"DAT_DIO","DAT_PIN":"DAT_DIO","DAT_POU":"DAT_DIO",\
                        #"DAT_ANA":"DAT_AD","DAT_PAN":"DAT_AD"\
                        #}
gListSpecialSubDATHeader = gDictSpecialDATHeader.keys()#["DAT_DIN","DAT_DOU","DAT_PIN","DAT_POU","DAT_ANA","DAT_PAN"]

#if the include path changed ,you should change this function
#generate include path is :
#include ".\..\..\..\DAT\DAT_DIO\DAT_DIN\DAT_DIN.h"
#include ".\..\..\..\DAT\DAT_BUZ\DAT_BUZ.h"
def GetHFilePathAndModelName(strPath):
    listPath = strPath.split("\\")
    #use the list compression to remove some unused element
    listPath = [each for each in listPath if each != ""]
    listPath.remove(gStrSubSource)
    listPath.remove(gStrSubPLFICU)
    listPath.remove("..")
    return ("\\".join(listPath),listPath[-1])

def GetNormalIncludeFormat(strModelName,strHFileName,strPathName, strType):
    return '''
#ifdef c%(ModelName)s_%(Type)sINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "%(HFileName)s"
	#else
	#include "%(PathName)s\%(HFileName)s"
	#endif
#endif\n
'''%{'ModelName':strModelName,'HFileName':strHFileName,'PathName':strPathName,"Type":strType}

def GetExportFile(strPath, dictData, dictFunc,dictType):
    for root, dirs,files in os.walk(strPath):
        for strEachFileName in files:
            #process DAT_XXX_DATAEXPORT.h
            if gStrDATExportFile.upper() in strEachFileName.upper():
                dictData[strEachFileName]=root

            #process DAT_XXX_FUNCEXPORT.h
            if gStrFuncExportFile.upper() in strEachFileName.upper():
                dictFunc[strEachFileName]=root

            #process DAT_XXX_FUNCEXPORT.h
            if gStrTypeExportFile.upper() in strEachFileName.upper():
                dictType[strEachFileName]=root



def WriteDictToFile(dictDATAOrFUNC,fHandleDATAOrFUNC,strType):
    global gSetSERChlName
    for eachKey in dictDATAOrFUNC:
        #writhe file include
        strPath,strModelName = GetHFilePathAndModelName(dictDATAOrFUNC[eachKey])
        #store each channel into set,just avoid repeated channel name
        # #ifdef cDAT_XXX_DATAINCLUDE
        gSetSERChlName.add("//#define c%s_%sINCLDUE\n"%(strModelName,strType))
        fHandleDATAOrFUNC.write(GetNormalIncludeFormat(strModelName,eachKey,strPath,strType))


def GenSCC2HIncludeFormat(strHFileName):
    return '''//this scope judge the SERChannel because the following file
//is auto generated by SCC2 tools.
#ifdef cHeadIncludeType_Directly
#include "%(hFileName)s
#else
#include ".\..\..\SCC2Gen\Gen\%(hFileName)s"
#endif\n\n
'''%{'hFileName':strHFileName}


def GenSpecialDATIncludeFormat(strHFileName,strDirName):
    return '''//here include special DAT file for data read and write
#ifdef cHeadIncludeType_Directly
#include "%(hFileName)s.h
#else
#include ".\..\..\DAT\%(DirName)s\%(hFileName)s\%(hFileName)s.h"
#endif\n\n
'''%{'hFileName':strHFileName,'DirName':strDirName}


def WriteSCC2HeaderInclude(fHandleDATAOrFUNC):
    global gStrSCC2GenPath
    global gListSpecialSubDATHeader

    strHFileName = ''
    for strPathName in glob.glob(gStrSCC2GenPath+"*.h"):
        strHFileName=os.path.basename(strPathName)
        if strHFileName[:-3] in gListSpecialSubDATHeader:
            fHandleDATAOrFUNC.write(GenSpecialDATIncludeFormat(strHFileName[:-3],gDictSpecialDATHeader[strHFileName[:-3]]))
        if "DAT" in strHFileName:
            #fHandleDATAOrFUNC.write(GenSCC2HIncludeFormat(strHFileName))
            pass

''''
1.01:
    change dirtory name and location
2.00---2016-04-16-15
    1:bug fix about removing comment code
    2:remove the generated date and author
'''
def PrintVersion():
    strVersion = "1.01"
    print "%s version is %s"%(os.path.basename(sys.argv[0]),strVersion)

def GetGenLog():
    strTime =  ("//This file is auto generated by %s"%(os.path.basename(sys.argv[0]) ))
    strName = "//This file is generated by %s"%getpass.getuser()
    return strTime + "\n" #+ strName + "\n\n"

#将\XXX\YYY替换为真正的路径
def SubRealSourcePath(strSub):
    global gStrSubSource
    global gStrSubPLFICU
    strReg = r".+(\\(\w+)\\(\w+))\\LAP\\LAP_SUP"
    regXY = r"\\XXX\\YYY"
    for root,dirs,files in os.walk(r".\..\..\.."):#搜索当前路径
        for Each in files:
            if Each == "LAP_SUP.c": #找到LAP_SUP.c，将LAP文件夹前面两层路径提取出来
                listRealPath = re.findall(strReg,root)
                gStrSubSource = listRealPath[0][1]
                gStrSubPLFICU = listRealPath[0][2]

                strRealPath = re.sub(regXY,listRealPath[0][0],strSub)#将\XXX\YYY替换为真正的路径

                return strRealPath

if __name__ == '__main__':
    gStrDATPath = SubRealSourcePath(gStrDATPath)
    gStrLAPPath = SubRealSourcePath(gStrLAPPath)
    gStrSERINCLUDEPath = SubRealSourcePath(gStrSERINCLUDEPath)
    gStrSCC2GenPath = SubRealSourcePath(gStrSCC2GenPath)

    PrintVersion()
    strGenLog = GetGenLog()
    GetExportFile(gStrDATPath,gDictDATDATAEXPORTPath,gDictDATFUNCEXPORTPath,gDictDATTYPEEXPORTPath)
    GetExportFile(gStrLAPPath,gDictDATDATAEXPORTPath,gDictDATFUNCEXPORTPath,gDictDATTYPEEXPORTPath)


    fSERChannelHandle = open(gStrSER_CHANNEL_H,"w")
    fSERDATAExpHandle = open(gStrSER_DATAExp_H,"w")
    fSERFUNCExpHandle = open(gStrSER_FUNCExp_H,"w")
    fSERTYPEExpHandle = open(gStrSER_TYPEExp_H,"w")

    #write SER_CHANNELS.h file header
    fSERChannelHandle.write(strGenLog)
    fSERChannelHandle.write(gStrCHANNELSHHeader)

    #write SER_DATAEXPORT_INCLUDE.h
    fSERDATAExpHandle.write(strGenLog)
    fSERDATAExpHandle.write(gStrSERDATAExpHeader1+gStrSERExpHeader)

    #write SER_FUNCEXPORT_INCLUDE.h
    fSERFUNCExpHandle.write(strGenLog)
    fSERFUNCExpHandle.write(gStrSERFUNCExpHeader1+gStrSERExpHeader)

    #write SER_TYPEEXPORT_INCLUDE.h
    fSERTYPEExpHandle.write(strGenLog)
    fSERTYPEExpHandle.write(gStrSERTYPEExpHeaer1 + gStrSERExpHeader)


    WriteDictToFile(gDictDATDATAEXPORTPath,fSERDATAExpHandle,"DATA")
    WriteDictToFile(gDictDATFUNCEXPORTPath,fSERFUNCExpHandle,"FUNC")
    WriteDictToFile(gDictDATTYPEEXPORTPath,fSERTYPEExpHandle,"TYPE")

    for each in gSetSERChlName:
        fSERChannelHandle.write(each)

    WriteSCC2HeaderInclude(fSERDATAExpHandle)
    WriteSCC2HeaderInclude(fSERFUNCExpHandle)

    fSERChannelHandle.write("\n#endif")
    fSERDATAExpHandle.write("\n#endif")
    fSERFUNCExpHandle.write("\n#endif")
    fSERTYPEExpHandle.write("\n#endif")

    fSERTYPEExpHandle.close()
    fSERChannelHandle.close()
    fSERDATAExpHandle.close()
    fSERFUNCExpHandle.close()

    #copy file to SER_INCLUDE folder
    shutil.move(gStrSER_CHANNEL_H,gStrSERINCLUDEPath+gStrSER_CHANNEL_H)
    shutil.move(gStrSER_DATAExp_H,gStrSERINCLUDEPath+gStrSER_DATAExp_H)
    shutil.move(gStrSER_FUNCExp_H,gStrSERINCLUDEPath+gStrSER_FUNCExp_H)
    shutil.move(gStrSER_TYPEExp_H,gStrSERINCLUDEPath+gStrSER_TYPEExp_H)
