# coding=utf-8
#SF=special file, for example:XXX_XXX_RunIn.h, all those files will
#be collected into a new file RunIn_Include.h for special usage.
#you just define the list like gListRunInNames, then call ProcessSF,
#all done!
import sys
import os
import time
import getpass
import shutil
import re

gStrDATPath = r".\..\..\..\XXX\YYY\DAT\\"
gStrLAPPath = r".\..\..\..\XXX\YYY\LAP\\"
gStrSERPath = r".\..\..\..\XXX\YYY\SER\\"
gStrTOSPath = r".\..\..\..\XXX\YYY\TOS\\"


gStrRunInFile = r"runin.h"
gStrGIL_INCLUDE_H = r"RunIn_Include.h"
gRunInHeader = '''#ifndef IS_INCLUDED_RunIn_INCLUDE_H
#define IS_INCLUDED_RunIn_INCLUDE_H


'''
#lsit[0]:special file tailer flag
#list[1]:generated new file name
#list[2]:generated new file header
#list[3]:the new generated file will be moved here,
#usually this is a folder name.




gFileTailer = "#endif"
gDATHeader='''//DAT Components
'''
gLAPHeader='''//LAP Components
'''
gSERHeader = '''//SER Components
'''


def IncludeFormat(strPath):
    return '#include "'+strPath+'" \n'

def GetSFFilePath(strPath,strList):
    listJILFiles = []
    strAllFiels = ""
    for root, dirs,files in os.walk(strPath):
        strAllFiels = "".join(files)
        for strEachFileName in files:
            if strList[0] in strEachFileName.lower():
                if strPath != gStrTOSPath:
                    listJILFiles.append(strEachFileName)
    return listJILFiles


def DelJILAndIncludeFile(strPath,strList):
  if os.path.exists(strList[1]):
        os.remove(strList[1])

'''
1.00
    create file
'''
def PrintVersion():
    strVersion = "1.00"
    print "%s version is %s"%(os.path.basename(sys.argv[0]),strVersion)


def GetGenLog():
    strTime =  ("//This file is auto generated by %s, generation time: %s"%(os.path.basename(sys.argv[0]) ,time.strftime('%Y-%m-%d %X', time.localtime() )))
    strName = "//This file is generated by %s"%getpass.getuser()
    return strTime + "\n" + strName + "\n\n"


def ProcessSF(strList):
    fHandle = open(strList[1],'w')
    fHandle.write(GetGenLog())
    fHandle.write(strList[2])

    fHandle.write(gDATHeader)
    for strEach in GetSFFilePath(gStrDATPath,strList):
        fHandle.write(IncludeFormat(strEach))

    fHandle.write("\n\n\n" + gLAPHeader)
    for strEach in GetSFFilePath(gStrLAPPath,strList):
        fHandle.write(IncludeFormat(strEach))

    fHandle.write("\n\n\n" + gSERHeader+"\n")
    for strEach in GetSFFilePath(gStrSERPath,strList):
        fHandle.write(IncludeFormat(strEach))

    fHandle.write(gFileTailer)
    fHandle.close()

    #copy strList[1] to LAP_XXX folder
    #shutil.copy(strList[1], gStrLAPPath + strList[3]+r"\\"+strList[1])
    shutil.copy(strList[1],  strList[-1])
    DelJILAndIncludeFile(r".\\",strList)


#将\XXX\YYY替换为真正的路径
def SubRealSourcePath(strSub):
    strReg = r".+(\\\w+\\\w+)\\LAP\\LAP_SUP"
    regXY = r"\\XXX\\YYY"
    for root,dirs,files in os.walk(r".\..\..\.."):#搜索当前路径
        for Each in files:
            if Each == "LAP_SUP.c": #找到LAP_SUP.c，将LAP文件夹前面两层路径提取出来
                listRealPath = re.findall(strReg,root)

                strRealPath = re.sub(regXY,listRealPath[0],strSub)#将\XXX\YYY替换为真正的路径

                return strRealPath

if __name__ == '__main__':

    gStrDATPath = SubRealSourcePath(gStrDATPath)
    gStrLAPPath = SubRealSourcePath(gStrLAPPath)
    gStrSERPath = SubRealSourcePath(gStrSERPath)
    gStrTOSPath = SubRealSourcePath(gStrTOSPath)

    gListRunInNames = [r"runin.h", r"RunIn_Include.h",gRunInHeader,gStrLAPPath+"LAP_RUNIN"]#此句要放在替换真正的路径之后

    PrintVersion()
    ProcessSF(gListRunInNames)
