# coding=utf-8
import sys
import re
import os
import glob
import time
import getpass

gStrSCC2GenPath = r".\..\..\..\XXX\YYY\SCC2Gen\GEN\\"

gStrOldIncludeSt = '#include "deftypes.h"'
gStrNewIncludeStr = '''#include "ARCH_CFG.h"

#ifdef cHeadIncludeType_Directly
#include "deftypes.h"
#else
#include ".\..\..\LIB\LIB_API\deftypes.h"
#endif\n\n'''


gStrOldReadType = 'mDATRead'
gStrNewReadType = 'mSERRead'
gStrOldWriteType = 'mDATWrite'
gStrNewWriteType = 'mSERWrite'

def GetCurDir():
    strPath = sys.path[0]
    if os.path.isdir(strPath):
        return strPath
    elif os.path.isfile(strPath):
        return os.path.dirname(strPath)

def IsIncludeStr(strFileContent,strSearched):
    if strSearched in strFileContent:
        return True
    else:
        return False


def ReplaceStr(strOldFileContent,strNew,strOriginal):
    objReg = re.compile(strOriginal)
    strNewFileContent,intNum = objReg.subn(strNew,strOldFileContent)
    return strNewFileContent

def ProcessEachHeaderFile(strFileName):
    fHandle = open(strFileName,'r')
    strOldFileContent = fHandle.read()
    strNewFielContent = strOldFileContent
    bIsFileChanged = False

    if gStrOldIncludeSt in strNewFielContent:
        strNewFielContent = ReplaceStr(strNewFielContent,gStrNewIncludeStr,gStrOldIncludeSt)
        bIsFileChanged = True

    if gStrOldReadType in strNewFielContent:
        strNewFielContent = ReplaceStr(strNewFielContent,gStrNewReadType,gStrOldReadType)
        bIsFileChanged = True

    if gStrOldWriteType in strNewFielContent:
        strNewFielContent = ReplaceStr(strNewFielContent,gStrNewWriteType,gStrOldWriteType)
        bIsFileChanged = True

    fHandle.close()


    if bIsFileChanged:
        fHandle = open(strFileName,'w')
        fHandle.write(GetGenLog())
        fHandle.write(strNewFielContent)
        fHandle.close

'''
1.01
    change the dirtory name and location
2.00---2016-04-16-15
    1:bug fix about removing comment code
    2:remove the generated date and author
'''
def PrintVersion():
    strVersion = "1.01"
    print "%s version is %s"%(os.path.basename(sys.argv[0]),strVersion)

def GetGenLog():
    strTime =  ("//This file is auto generated by %s"%(os.path.basename(sys.argv[0]) ))
    strName = "//This file is generated by %s"%getpass.getuser()
    return strTime + "\n" #+ strName + "\n\n"

#将\XXX\YYY替换为真正的路径
def SubRealSourcePath(strSub):
    strReg = r".+(\\\w+\\\w+)\\LAP\\LAP_SUP"
    regXY = r"\\XXX\\YYY"
    for root,dirs,files in os.walk(r".\..\..\.."):#搜索当前路径
        for Each in files:
            if Each == "LAP_SUP.c": #找到LAP_SUP.c，将LAP文件夹前面两层路径提取出来
                listRealPath = re.findall(strReg,root)

                strRealPath = re.sub(regXY,listRealPath[0],strSub)#将\XXX\YYY替换为真正的路径

                return strRealPath

if __name__ == '__main__':
    gStrSCC2GenPath = SubRealSourcePath(gStrSCC2GenPath)

    PrintVersion()
    for strFileName in glob.glob(gStrSCC2GenPath+"*.h"):
        ProcessEachHeaderFile(strFileName)




