//This file is auto generated by CanTimeout.exe 

#ifndef SOURCE_PLFICU_DAT_DAT_CAN_DAT_CPL_DAT_CPL_TABLETIMEOUT_H_
#define SOURCE_PLFICU_DAT_DAT_CAN_DAT_CPL_DAT_CPL_TABLETIMEOUT_H_

const U32 cau32DATCplTableTimeoutMs[cDATCdl_NbUURx] =
{
    5000, //Handle  0
    5000, //Handle  1
    2000, //Handle  2
    2000, //Handle  3
    2000, //Handle  4
    2000, //Handle  5
    2000, //Handle  6
    2000, //Handle  7
    2000, //Handle  8
    2000, //Handle  9
    2000, //Handle  10
    2000, //Handle  11
    2000, //Handle  12
    2000, //Handle  13
    2000, //Handle  14
    2000, //Handle  15
    2000, //Handle  16
    2000, //Handle  17
    2000, //Handle  18
    2000, //Handle  19
};


#endif /* SOURCE_PLFICU_DAT_DAT_CAN_DAT_CPL_DAT_CPL_TABLETIMEOUT_H_ */
