// this file is generated by CanEmission.py

#define mMacroDatCplDiagEnableAppRx() \
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleICUCMD_0x150);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleICUCMD1_0x160);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleBCM_4_0x392);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleRLDCM_1_0x3AE);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleRCM_1_0x2D1);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleFRZCU_1_0x2AB);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleFLZCU_9_0x49D);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleFLZCU_5_0x35B);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleFLZCU_1_0x23B);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleTMS_1_0x494);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleRCM_3_0x2DB);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleRLDCM_2_0x2C8);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleRLDCM_3_0x437);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleRLDRM_1_0x2E8);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleRRDCM_1_0x3BE);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleRLCR_1_0x447);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleRLCR_2_0x450);\
    mDATCanMsgRxEnable(cDATCdlD_UURxHandleICC_COM_8_0x510);\


#define mMacroDatCplDiagDisableAppRx() \
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleICUCMD_0x150);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleICUCMD1_0x160);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleBCM_4_0x392);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleRLDCM_1_0x3AE);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleRCM_1_0x2D1);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleFRZCU_1_0x2AB);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleFLZCU_9_0x49D);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleFLZCU_5_0x35B);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleFLZCU_1_0x23B);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleTMS_1_0x494);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleRCM_3_0x2DB);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleRLDCM_2_0x2C8);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleRLDCM_3_0x437);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleRLDRM_1_0x2E8);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleRRDCM_1_0x3BE);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleRLCR_1_0x447);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleRLCR_2_0x450);\
    mDATCanMsgRxDisable(cDATCdlD_UURxHandleICC_COM_8_0x510);\


#define mMacroDatCplDiagEnableAppTx() \
    mDATCanMsgTxEnable(cDATCdlD_UUTxHandleIouTxCmd_0x100);\
    mDATCanMsgTxEnable(cDATCdlD_UUTxHandleFLDCM_1_0x38E);\
    mDATCanMsgTxEnable(cDATCdlD_UUTxHandleIouTxCmd1_0x18FF1711);\
    mDATCanMsgTxEnable(cDATCdlD_UUTxHandleIouTxCmd2_0x120);\
    mDATCanMsgTxEnable(cDATCdlD_UUTxHandleIouTxCmd3_0x130);\
    mDATCanMsgTxEnable(cDATCdlD_UUTxHandleIouTxCmd4_0x140);\
    mDATCanMsgTxEnable(cDATCdlD_UUTxHandleNotUsed2_0xFFFFAABB);\
    mDATCanMsgTxEnable(cDATCdlD_UUTxHandleNotUsed1_0xFFFFAABB);\


#define mMacroDatCplDiagDisableAppTx() \
    mDATCanMsgTxDisable(cDATCdlD_UUTxHandleIouTxCmd_0x100);\
    mDATCanMsgTxDisable(cDATCdlD_UUTxHandleFLDCM_1_0x38E);\
    mDATCanMsgTxDisable(cDATCdlD_UUTxHandleIouTxCmd1_0x18FF1711);\
    mDATCanMsgTxDisable(cDATCdlD_UUTxHandleIouTxCmd2_0x120);\
    mDATCanMsgTxDisable(cDATCdlD_UUTxHandleIouTxCmd3_0x130);\
    mDATCanMsgTxDisable(cDATCdlD_UUTxHandleIouTxCmd4_0x140);\
    mDATCanMsgTxDisable(cDATCdlD_UUTxHandleNotUsed2_0xFFFFAABB);\
    mDATCanMsgTxDisable(cDATCdlD_UUTxHandleNotUsed1_0xFFFFAABB);\


