# coding=utf-8
######################################
######################################
###this file is used to rename IAR project
###
###
#####################################
#####################################
import sys
import re
import os
import glob
import time
import getpass

gOldIARProName = "ClusterPlatform"
gNewIARProName = "NewTest"


gTupleFolderSkip = ("Exe","List","Obj")
gTupleFileSkip = (".py",".exe")

def PrintVersion():
    strVersion = "1.00"
    print "%s version is %s"%(os.path.basename(sys.argv[0]),strVersion)

def GetGenLog():
    strTime =  ("//This file is auto generated by %s, generation time: %s"%(os.path.basename(sys.argv[0]) ,time.strftime('%Y-%m-%d %X', time.localtime() )))
    strName = "//This file is generated by %s"%getpass.getuser()
    return strTime + "\n" + strName + "\n\n"

def ProcessFile(strFileName,strFolder):
    if os.path.splitext(strFileName)[1].lower() in gTupleFileSkip:
        return

    strFileName = strFolder +"\\"+strFileName

    fHandle = open(strFileName,'r')
    strFHOldStr = fHandle.read()
    fHandle.close()

    strFHNewStr = ""
    if gOldIARProName in strFHOldStr:
        strFHNewStr = strFHOldStr.replace(gOldIARProName,gNewIARProName)
        fHandle = open(strFileName,'w')
        fHandle.write(strFHNewStr)
        fHandle.close()

    #rename file name
    if gOldIARProName in strFileName:
        os.rename(strFileName,strFileName.replace(gOldIARProName,gNewIARProName))


def RenameFiles(strPath):
    if not os.path.exists(strPath):
        print "input path error ,please check"
        exit()
        return;

    for root, dirs,files in os.walk(strPath):
        if dirs in gTupleFolderSkip:
            continue
        for strEachFileName in files:
            if "ddd" in strEachFileName:
                pass
            ProcessFile(strEachFileName,root)


def CheckInputName(strOldProFile, strNewProFile):
    if " " in strOldProFile or " " in strNewProFile:
        print "Project name can not contain space,please check"
        exit

gStrUsage = """
1:copy this ProjectRename.exe to IAR flder
2:open command line and change into IAR folder
3:imput this:ProjectName.exe OldProjectName NewProjectName
"""

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print "please use this in command line,and input new project name and old project name\n"
        print "bye\b"
        exit()
    CheckInputName(sys.argv[1],sys.argv[2])
    gOldIARProName  = sys.argv[1]
    gNewIARProName =  sys.argv[2]

    PrintVersion()
    RenameFiles(".\\")
    print "OK and Over"






