//This file is auto generated by AutoGenSERChannels.exe
#ifndef I_SER_TYPEEXPORT_INCLUDE_H
#define I_SER_TYPEEXPORT_INCLUDE_H (1)


/*-------------------------------------------------------------------------
  Included files to resolve specific definitions in this file

  #include <system_file_name.h>
  #include "project_file_name.h"
  -------------------------------------------------------------------------*/
#include "ARCH_CFG.h"

#ifdef cHeadIncludeType_Directly
#include "SER_LIB.h"
#else
#include ".\..\SER_LIB.h"
#endif

//------------------------------------------------------------------------------
// Local constants
//------------------------------------------------------------------------------

#ifdef cDAT_DTC_TYPEINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_DTC_TYPEEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_DTC\DAT_DTC_TYPEEXPORT.h"
	#endif
#endif


#ifdef cDAT_BLDC_TYPEINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_BLDC_TYPEEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_BLDC\DAT_BLDC_TYPEEXPORT.h"
	#endif
#endif


#ifdef cDAT_MOD_TYPEINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_MOD_TYPEEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_MOD\DAT_MOD_TYPEEXPORT.h"
	#endif
#endif


#ifdef cDAT_CAN_TYPEINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_CAN_TYPEEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_CAN\DAT_CAN_TYPEEXPORT.h"
	#endif
#endif


#ifdef cDAT_BSDC_TYPEINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_BSDC_TYPEEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_BSDC\DAT_BSDC_TYPEEXPORT.h"
	#endif
#endif


#ifdef cDAT_CANNM_TYPEINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_CANNM_TYPEEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_CANNM\DAT_CANNM_TYPEEXPORT.h"
	#endif
#endif


#ifdef cLAP_LOCK_TYPEINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "LAP_LOCK_TYPEEXPORT.h"
	#else
	#include ".\..\..\LAP\LAP_LOCK\LAP_LOCK_TYPEEXPORT.h"
	#endif
#endif


#endif