//This file is auto generated by AutoGenSERChannels.exe, generation time: 2016-03-04 09:22:16
//This file is generated by sunms

#ifndef I_SER_CHANNELS_H
#define I_SER_CHANNELS_H


#define cSERChannelDAT_MOD
#define cSERChannelDAT_LCD
#define cSERChannelDAT_MOT
#define cSERChannelDAT_MMI
#define cSERChannelDAT_AD
#define cSERChannelDAT_BLK
#define cSERChannelDAT_CPU
#define cSERChannelDAT_PWM
#define cSERChannelDAT_CVT
#define cSERChannelDAT_DOU
#define cSERChannelDAT_BUZ
#define cSERChannelDAT_DTC
#define cSERChannelDAT_RTC
#define cSERChannelDAT_CAN
#define cSERChannelDAT_BAT
#define cSERChannelDAT_EEP

#endif