//This file is auto generated by AutoGenSERChannels.exe
#ifndef I_SER_FUNCEXPORT_INCLUDE_H
#define I_SER_FUNCEXPORT_INCLUDE_H (1)

/*-------------------------------------------------------------------------
  Included files to resolve specific definitions in this file

  #include <system_file_name.h>
  #include "project_file_name.h"
  -------------------------------------------------------------------------*/
#include "ARCH_CFG.h"

#ifdef cHeadIncludeType_Directly
#include "SER_LIB.h"
#else
#include ".\..\SER_LIB.h"
#endif

//------------------------------------------------------------------------------
// Local constants
//------------------------------------------------------------------------------

#ifdef cDAT_DTC_FUNCINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_DTC_FUNCEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_DTC\DAT_DTC_FUNCEXPORT.h"
	#endif
#endif


#ifdef cDAT_CPU_FUNCINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_CPU_FUNCEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_CPU\DAT_CPU_FUNCEXPORT.h"
	#endif
#endif


#ifdef cDAT_DOU_FUNCINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_DOU_FUNCEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_DIO\DAT_DOU\DAT_DOU_FUNCEXPORT.h"
	#endif
#endif


#ifdef cLAP_DIAG_FUNCINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "LAP_DIAG_FUNCEXPORT.h"
	#else
	#include ".\..\..\LAP\LAP_DIAG\LAP_DIAG_FUNCEXPORT.h"
	#endif
#endif


#ifdef cDAT_BAT_FUNCINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_BAT_FUNCEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_BAT\DAT_BAT_FUNCEXPORT.h"
	#endif
#endif


#ifdef cDAT_CAN_FUNCINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_CAN_FUNCEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_CAN\DAT_CAN_FUNCEXPORT.h"
	#endif
#endif


#endif