//This file is auto generated by AutoGenSERChannels.exe
#ifndef I_SER_DATAEXPORT_INCLUDE_H
#define I_SER_DATAEXPORT_INCLUDE_H (1)


/*-------------------------------------------------------------------------
  Included files to resolve specific definitions in this file

  #include <system_file_name.h>
  #include "project_file_name.h"
  -------------------------------------------------------------------------*/
#include "ARCH_CFG.h"

#ifdef cHeadIncludeType_Directly
#include "SER_LIB.h"
#else
#include ".\..\SER_LIB.h"
#endif

//------------------------------------------------------------------------------
// Local constants
//------------------------------------------------------------------------------

#ifdef cDAT_DTC_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_DTC_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_DTC\DAT_DTC_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_EEP_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_EEP_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_EEP\DAT_EEP_DATAEXPORT.h"
	#endif
#endif


#ifdef cLAP_RUNIN_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "LAP_RUNIN_DATAEXPORT.h"
	#else
	#include ".\..\..\LAP\LAP_RUNIN\LAP_RUNIN_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_BLDC_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_BLDC_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_BLDC\DAT_BLDC_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_CANNM_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_CANNM_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_CANNM\DAT_CANNM_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_DOU_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_DOU_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_DIO\DAT_DOU\DAT_DOU_DATAEXPORT.h"
	#endif
#endif


#ifdef cLAP_DIAG_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "LAP_DIAG_DATAEXPORT.h"
	#else
	#include ".\..\..\LAP\LAP_DIAG\LAP_DIAG_DATAEXPORT.h"
	#endif
#endif


#ifdef cLAP_LOCK_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "LAP_LOCK_DATAEXPORT.h"
	#else
	#include ".\..\..\LAP\LAP_LOCK\LAP_LOCK_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_BAT_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_BAT_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_BAT\DAT_BAT_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_AD_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_AD_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_AD\DAT_AD_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_MOD_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_MOD_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_MOD\DAT_MOD_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_CPU_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_CPU_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_CPU\DAT_CPU_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_DIN_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_DIN_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_DIO\DAT_DIN\DAT_DIN_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_CAN_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_CAN_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_CAN\DAT_CAN_DATAEXPORT.h"
	#endif
#endif


#ifdef cDAT_BSDC_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "DAT_BSDC_DATAEXPORT.h"
	#else
	#include ".\..\..\DAT\DAT_BSDC\DAT_BSDC_DATAEXPORT.h"
	#endif
#endif


#ifdef cLAP_CAN_DATAINCLUDE
	#ifdef cHeadIncludeType_Directly
	#include "LAP_CAN_DATAEXPORT.h"
	#else
	#include ".\..\..\LAP\LAP_CAN\LAP_CAN_DATAEXPORT.h"
	#endif
#endif


#endif