# coding=utf-8
import sys
import os
import time
import getpass
import shutil
import glob
import re
#这里要查找的Task结构体元素可能不全，所以
#筛选的条件要加宽
gReTask=r"\bTask\s{1,}\w+.*?[(Id\s{0,}=\s{0,}\"\w+)|(Priority.*?\d+)|(Fct\s{0,}=\s{0,}\"\w+)]\s*?;.*?\};"
gReRemoveComment1 = "(\/\*.*?\*\/)"
gReRemoveComment2 = r"//.*"
gStrTaskInfoName = "TaskInfo.txt"


gStrJILFile = ".jil"
gStrGIL_INCLUDE_H = r"JIL_Include.h"
gFileHeader = '''#ifndef IS_INCLUDED_JIL_INCLUDE_H
#define IS_INCLUDED_JIL_INCLUDE_H


'''

gFileTailer = "#endif"

gTOSHeader = '''
//TOS Components
#include "TOS.JIL"
'''

gDATHeader='''//DAT Components
'''

gLAPHeader='''//LAP Components
'''

gSERHeader = '''//SER Components'''

gStrDATPath = r".\..\..\..\XXX\YYY\DAT\\"
gStrLAPPath = r".\..\..\..\XXX\YYY\LAP\\"
gStrSERPath = r".\..\..\..\XXX\YYY\SER\\"
gStrTOSPath = r".\..\..\..\XXX\YYY\TOS\\"


def IncludeFormat(strPath):
    return '#include "'+strPath+'" \n'

def GetJILFilePath(strPath):
    listJILFiles = []
    strAllFiels = ""
    for root, dirs,files in os.walk(strPath):
        strAllFiels = "".join(files)
        for strEachFileName in files:
            if gStrJILFile in strEachFileName.lower():
                if strPath != gStrTOSPath:
                    listJILFiles.append(strEachFileName)
                #copy JIL file into current folder
                shutil.copy(root+r"\\"+strEachFileName,strEachFileName)
    return listJILFiles


def DelJILAndIncludeFile(strPath):
    strAllFiels = ""

    if os.path.exists(gStrGIL_INCLUDE_H):
        os.remove(gStrGIL_INCLUDE_H)

    for root, dirs,files in os.walk(strPath):
        strAllFiels = "".join(files)
        for strEachFileName in files:
            if gStrJILFile in strEachFileName.lower():
                os.remove(strEachFileName)


def GetTaskInfoFromFile(strJILFileName,fHandleResult):
    global gReTask
    global gReRemoveComment1
    global gReRemoveComment2

    if strJILFileName == "DAT_PNL.jil" or strJILFileName == "DAT_DTC.jil":
        pass

    fHandle = open(strJILFileName,"r")
    strContent = fHandle.read()
    #注意：匹配//时，一定不能使用flags=re.S，这个表示将所有的字符当成
    #一个串
    strContent = re.sub(gReRemoveComment2,"",strContent)
    strContent = re.sub(gReRemoveComment1,"",strContent,flags=re.S)


    for each in (re.findall(gReTask,strContent,re.S)):
        fHandleResult.write("\n*****************************************************\n")
        fHandleResult.write(strJILFileName+"\n")
        fHandleResult.write(each+"\n")
    fHandle.close()


'''
1.01
    change the dirtory name and location
2.00 2016-4-16-16
    1:bug fix about removing comment code
    2:remove the generated date and author
'''
def PrintVersion():
    strVersion = "1.01"
    print "%s version is %s"%(os.path.basename(sys.argv[0]),strVersion)


def GetGenLog():
    strTime =  ("//This file is auto generated by %s"%(os.path.basename(sys.argv[0]) ))
    strName = "//This file is generated by %s"%getpass.getuser()
    return strTime + "\n" #+ strName + "\n\n"

#将\XXX\YYY替换为真正的路径
def SubRealSourcePath(strSub):
    strReg = r".+(\\\w+\\\w+)\\LAP\\LAP_SUP"
    regXY = r"\\XXX\\YYY"
    for root,dirs,files in os.walk(r".\..\..\.."):#搜索当前路径
        for Each in files:
            if Each == "LAP_SUP.c": #找到LAP_SUP.c，将LAP文件夹前面两层路径提取出来
                listRealPath = re.findall(strReg,root)

                strRealPath = re.sub(regXY,listRealPath[0],strSub)#将\XXX\YYY替换为真正的路径

                return strRealPath


if __name__ == '__main__':

    gStrDATPath = SubRealSourcePath(gStrDATPath)
    gStrLAPPath = SubRealSourcePath(gStrLAPPath)
    gStrSERPath = SubRealSourcePath(gStrSERPath)
    gStrTOSPath = SubRealSourcePath(gStrTOSPath)

    PrintVersion()

    DelJILAndIncludeFile(r".\\")

    fHandle = open(gStrGIL_INCLUDE_H,'w')
    fHandle.write(GetGenLog())
    fHandle.write(gFileHeader)
    fHandle.write(gTOSHeader+"\n\n\n")

    fHandle.write(gDATHeader)
    for strEach in GetJILFilePath(gStrDATPath):
        fHandle.write(IncludeFormat(strEach))

    fHandle.write("\n\n\n" + gLAPHeader)
    for strEach in GetJILFilePath(gStrLAPPath):
        fHandle.write(IncludeFormat(strEach))

    fHandle.write("\n\n\n" + gSERHeader+"\n")
    for strEach in GetJILFilePath(gStrSERPath):
        fHandle.write(IncludeFormat(strEach))

    fHandle.write(gFileTailer)
    fHandle.close()

    #just copy TOS\ JIL into here
    GetJILFilePath(gStrTOSPath)

    #copy gStrGIL_INCLUDE_H to LAP_SUP folder
    shutil.copy(gStrGIL_INCLUDE_H, gStrLAPPath + r"LAP_SUP\\"+gStrGIL_INCLUDE_H)
    #note:the JIL and H files are deleted in PlatformEntry.bat, so hrer you must not delete
    #JIL file, because the following step is analysing all jil files.

    #now begin collect all task info from each JIL file
    fHandleTaskResult = open(gStrTaskInfoName,'w')
    for strFileName in glob.glob("*.jil"):
        GetTaskInfoFromFile(strFileName,fHandleTaskResult)

    fHandleTaskResult.close()
    shutil.move(gStrTaskInfoName, gStrLAPPath + r"LAP_SUP\\"+gStrTaskInfoName)
